// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="hls_xfft2real_hls_xfft2real,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7k325t-ffg676-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=6.821000,HLS_SYN_LAT=3086,HLS_SYN_TPT=1032,HLS_SYN_MEM=50,HLS_SYN_DSP=0,HLS_SYN_FF=2944,HLS_SYN_LUT=44015,HLS_VERSION=2020_2}" *)

module hls_xfft2real (
        ap_clk,
        ap_rst_n,
        din_V_TDATA,
        dout_V_TDATA,
        ap_start,
        din_V_TVALID,
        din_V_TREADY,
        dout_V_TVALID,
        dout_V_TREADY,
        ap_done,
        ap_ready,
        ap_idle
);


input   ap_clk;
input   ap_rst_n;
input  [63:0] din_V_TDATA;
output  [63:0] dout_V_TDATA;
input   ap_start;
input   din_V_TVALID;
output   din_V_TREADY;
output   dout_V_TVALID;
input   dout_V_TREADY;
output   ap_done;
output   ap_ready;
output   ap_idle;

 reg    ap_rst_n_inv;
wire   [31:0] descramble_buf_0_M_real_V_i_q0;
wire   [31:0] descramble_buf_0_M_real_V_i_q1;
wire   [31:0] descramble_buf_0_M_real_V_t_q0;
wire   [31:0] descramble_buf_0_M_real_V_t_q1;
wire   [31:0] descramble_buf_1_M_real_V_i_q0;
wire   [31:0] descramble_buf_1_M_real_V_i_q1;
wire   [31:0] descramble_buf_1_M_real_V_t_q0;
wire   [31:0] descramble_buf_1_M_real_V_t_q1;
wire   [31:0] descramble_buf_0_M_imag_V_i_q0;
wire   [31:0] descramble_buf_0_M_imag_V_i_q1;
wire   [31:0] descramble_buf_0_M_imag_V_t_q0;
wire   [31:0] descramble_buf_0_M_imag_V_t_q1;
wire   [31:0] descramble_buf_1_M_imag_V_i_q0;
wire   [31:0] descramble_buf_1_M_imag_V_i_q1;
wire   [31:0] descramble_buf_1_M_imag_V_t_q0;
wire   [31:0] descramble_buf_1_M_imag_V_t_q1;
wire   [30:0] filter_buf_0_M_real_V_i_q0;
wire   [30:0] filter_buf_0_M_real_V_i_q1;
wire   [30:0] filter_buf_0_M_real_V_t_q0;
wire   [30:0] filter_buf_0_M_real_V_t_q1;
wire   [30:0] filter_buf_1_M_real_V_i_q0;
wire   [30:0] filter_buf_1_M_real_V_i_q1;
wire   [30:0] filter_buf_1_M_real_V_t_q0;
wire   [30:0] filter_buf_1_M_real_V_t_q1;
wire   [30:0] filter_buf_0_M_imag_V_i_q0;
wire   [30:0] filter_buf_0_M_imag_V_i_q1;
wire   [30:0] filter_buf_0_M_imag_V_t_q0;
wire   [30:0] filter_buf_0_M_imag_V_t_q1;
wire   [30:0] filter_buf_1_M_imag_V_i_q0;
wire   [30:0] filter_buf_1_M_imag_V_i_q1;
wire   [30:0] filter_buf_1_M_imag_V_t_q0;
wire   [30:0] filter_buf_1_M_imag_V_t_q1;
wire   [23:0] twid_rom_M_real_V_i_q0;
wire   [23:0] twid_rom_M_real_V_t_q0;
wire   [23:0] twid_rom_M_imag_V_i_q0;
wire   [23:0] twid_rom_M_imag_V_t_q0;
wire   [23:0] twid_rom_conj_M_real_V_i_q0;
wire   [23:0] twid_rom_conj_M_real_V_t_q0;
wire   [22:0] twid_rom_conj_M_imag_V_i_q0;
wire   [22:0] twid_rom_conj_M_imag_V_t_q0;
wire    Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_ap_start;
wire    Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_ap_done;
wire    Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_ap_continue;
wire    Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_ap_idle;
wire    Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_ap_ready;
wire   [9:0] Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_real_V_address0;
wire    Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_real_V_ce0;
wire    Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_real_V_we0;
wire   [23:0] Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_real_V_d0;
wire   [9:0] Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_real_V_address1;
wire    Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_real_V_ce1;
wire    Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_real_V_we1;
wire   [23:0] Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_real_V_d1;
wire   [9:0] Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_imag_V_address0;
wire    Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_imag_V_ce0;
wire    Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_imag_V_we0;
wire   [23:0] Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_imag_V_d0;
wire   [9:0] Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_imag_V_address1;
wire    Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_imag_V_ce1;
wire    Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_imag_V_we1;
wire   [23:0] Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_imag_V_d1;
wire   [9:0] Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_real_V_address0;
wire    Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_real_V_ce0;
wire    Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_real_V_we0;
wire   [23:0] Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_real_V_d0;
wire   [9:0] Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_real_V_address1;
wire    Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_real_V_ce1;
wire    Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_real_V_we1;
wire   [23:0] Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_real_V_d1;
wire   [9:0] Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_imag_V_address0;
wire    Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_imag_V_ce0;
wire    Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_imag_V_we0;
wire   [22:0] Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_imag_V_d0;
wire   [9:0] Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_imag_V_address1;
wire    Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_imag_V_ce1;
wire    Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_imag_V_we1;
wire   [22:0] Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_imag_V_d1;
wire    ap_channel_done_twid_rom_conj_M_imag_V;
wire    Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_imag_V_full_n;
reg    ap_sync_reg_channel_write_twid_rom_conj_M_imag_V;
wire    ap_sync_channel_write_twid_rom_conj_M_imag_V;
wire    ap_channel_done_twid_rom_conj_M_real_V;
wire    Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_real_V_full_n;
reg    ap_sync_reg_channel_write_twid_rom_conj_M_real_V;
wire    ap_sync_channel_write_twid_rom_conj_M_real_V;
wire    ap_channel_done_twid_rom_M_imag_V;
wire    Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_imag_V_full_n;
reg    ap_sync_reg_channel_write_twid_rom_M_imag_V;
wire    ap_sync_channel_write_twid_rom_M_imag_V;
wire    ap_channel_done_twid_rom_M_real_V;
wire    Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_real_V_full_n;
reg    ap_sync_reg_channel_write_twid_rom_M_real_V;
wire    ap_sync_channel_write_twid_rom_M_real_V;
wire    Loop_realfft_be_buffer_proc3_U0_ap_start;
wire    Loop_realfft_be_buffer_proc3_U0_ap_done;
wire    Loop_realfft_be_buffer_proc3_U0_ap_continue;
wire    Loop_realfft_be_buffer_proc3_U0_ap_idle;
wire    Loop_realfft_be_buffer_proc3_U0_ap_ready;
wire   [8:0] Loop_realfft_be_buffer_proc3_U0_descramble_buf_0_M_imag_V_address0;
wire    Loop_realfft_be_buffer_proc3_U0_descramble_buf_0_M_imag_V_ce0;
wire    Loop_realfft_be_buffer_proc3_U0_descramble_buf_0_M_imag_V_we0;
wire   [31:0] Loop_realfft_be_buffer_proc3_U0_descramble_buf_0_M_imag_V_d0;
wire   [8:0] Loop_realfft_be_buffer_proc3_U0_descramble_buf_1_M_imag_V_address0;
wire    Loop_realfft_be_buffer_proc3_U0_descramble_buf_1_M_imag_V_ce0;
wire    Loop_realfft_be_buffer_proc3_U0_descramble_buf_1_M_imag_V_we0;
wire   [31:0] Loop_realfft_be_buffer_proc3_U0_descramble_buf_1_M_imag_V_d0;
wire    Loop_realfft_be_buffer_proc3_U0_din_V_TREADY;
wire   [8:0] Loop_realfft_be_buffer_proc3_U0_descramble_buf_0_M_real_V_address0;
wire    Loop_realfft_be_buffer_proc3_U0_descramble_buf_0_M_real_V_ce0;
wire    Loop_realfft_be_buffer_proc3_U0_descramble_buf_0_M_real_V_we0;
wire   [31:0] Loop_realfft_be_buffer_proc3_U0_descramble_buf_0_M_real_V_d0;
wire   [8:0] Loop_realfft_be_buffer_proc3_U0_descramble_buf_1_M_real_V_address0;
wire    Loop_realfft_be_buffer_proc3_U0_descramble_buf_1_M_real_V_ce0;
wire    Loop_realfft_be_buffer_proc3_U0_descramble_buf_1_M_real_V_we0;
wire   [31:0] Loop_realfft_be_buffer_proc3_U0_descramble_buf_1_M_real_V_d0;
wire    ap_channel_done_descramble_buf_1_M_real_V;
wire    Loop_realfft_be_buffer_proc3_U0_descramble_buf_1_M_real_V_full_n;
reg    ap_sync_reg_channel_write_descramble_buf_1_M_real_V;
wire    ap_sync_channel_write_descramble_buf_1_M_real_V;
wire    ap_channel_done_descramble_buf_0_M_real_V;
wire    Loop_realfft_be_buffer_proc3_U0_descramble_buf_0_M_real_V_full_n;
reg    ap_sync_reg_channel_write_descramble_buf_0_M_real_V;
wire    ap_sync_channel_write_descramble_buf_0_M_real_V;
wire    ap_channel_done_descramble_buf_1_M_imag_V;
wire    Loop_realfft_be_buffer_proc3_U0_descramble_buf_1_M_imag_V_full_n;
reg    ap_sync_reg_channel_write_descramble_buf_1_M_imag_V;
wire    ap_sync_channel_write_descramble_buf_1_M_imag_V;
wire    ap_channel_done_descramble_buf_0_M_imag_V;
wire    Loop_realfft_be_buffer_proc3_U0_descramble_buf_0_M_imag_V_full_n;
reg    ap_sync_reg_channel_write_descramble_buf_0_M_imag_V;
wire    ap_sync_channel_write_descramble_buf_0_M_imag_V;
wire    Loop_realfft_be_descramble_proc_U0_ap_start;
wire    Loop_realfft_be_descramble_proc_U0_ap_done;
wire    Loop_realfft_be_descramble_proc_U0_ap_continue;
wire    Loop_realfft_be_descramble_proc_U0_ap_idle;
wire    Loop_realfft_be_descramble_proc_U0_ap_ready;
wire   [8:0] Loop_realfft_be_descramble_proc_U0_filter_buf_0_M_imag_V_address0;
wire    Loop_realfft_be_descramble_proc_U0_filter_buf_0_M_imag_V_ce0;
wire    Loop_realfft_be_descramble_proc_U0_filter_buf_0_M_imag_V_we0;
wire   [30:0] Loop_realfft_be_descramble_proc_U0_filter_buf_0_M_imag_V_d0;
wire   [8:0] Loop_realfft_be_descramble_proc_U0_filter_buf_1_M_imag_V_address0;
wire    Loop_realfft_be_descramble_proc_U0_filter_buf_1_M_imag_V_ce0;
wire    Loop_realfft_be_descramble_proc_U0_filter_buf_1_M_imag_V_we0;
wire   [30:0] Loop_realfft_be_descramble_proc_U0_filter_buf_1_M_imag_V_d0;
wire   [8:0] Loop_realfft_be_descramble_proc_U0_filter_buf_0_M_real_V_address0;
wire    Loop_realfft_be_descramble_proc_U0_filter_buf_0_M_real_V_ce0;
wire    Loop_realfft_be_descramble_proc_U0_filter_buf_0_M_real_V_we0;
wire   [30:0] Loop_realfft_be_descramble_proc_U0_filter_buf_0_M_real_V_d0;
wire   [8:0] Loop_realfft_be_descramble_proc_U0_filter_buf_1_M_real_V_address0;
wire    Loop_realfft_be_descramble_proc_U0_filter_buf_1_M_real_V_ce0;
wire    Loop_realfft_be_descramble_proc_U0_filter_buf_1_M_real_V_we0;
wire   [30:0] Loop_realfft_be_descramble_proc_U0_filter_buf_1_M_real_V_d0;
wire   [8:0] Loop_realfft_be_descramble_proc_U0_descramble_buf_0_M_imag_V_address0;
wire    Loop_realfft_be_descramble_proc_U0_descramble_buf_0_M_imag_V_ce0;
wire   [8:0] Loop_realfft_be_descramble_proc_U0_descramble_buf_0_M_imag_V_address1;
wire    Loop_realfft_be_descramble_proc_U0_descramble_buf_0_M_imag_V_ce1;
wire   [8:0] Loop_realfft_be_descramble_proc_U0_descramble_buf_1_M_imag_V_address0;
wire    Loop_realfft_be_descramble_proc_U0_descramble_buf_1_M_imag_V_ce0;
wire   [8:0] Loop_realfft_be_descramble_proc_U0_descramble_buf_1_M_imag_V_address1;
wire    Loop_realfft_be_descramble_proc_U0_descramble_buf_1_M_imag_V_ce1;
wire   [8:0] Loop_realfft_be_descramble_proc_U0_descramble_buf_0_M_real_V_address0;
wire    Loop_realfft_be_descramble_proc_U0_descramble_buf_0_M_real_V_ce0;
wire   [8:0] Loop_realfft_be_descramble_proc_U0_descramble_buf_0_M_real_V_address1;
wire    Loop_realfft_be_descramble_proc_U0_descramble_buf_0_M_real_V_ce1;
wire   [8:0] Loop_realfft_be_descramble_proc_U0_descramble_buf_1_M_real_V_address0;
wire    Loop_realfft_be_descramble_proc_U0_descramble_buf_1_M_real_V_ce0;
wire   [8:0] Loop_realfft_be_descramble_proc_U0_descramble_buf_1_M_real_V_address1;
wire    Loop_realfft_be_descramble_proc_U0_descramble_buf_1_M_real_V_ce1;
wire   [9:0] Loop_realfft_be_descramble_proc_U0_twid_rom_M_real_V_address0;
wire    Loop_realfft_be_descramble_proc_U0_twid_rom_M_real_V_ce0;
wire   [9:0] Loop_realfft_be_descramble_proc_U0_twid_rom_M_imag_V_address0;
wire    Loop_realfft_be_descramble_proc_U0_twid_rom_M_imag_V_ce0;
wire    ap_channel_done_filter_buf_1_M_real_V;
wire    Loop_realfft_be_descramble_proc_U0_filter_buf_1_M_real_V_full_n;
reg    ap_sync_reg_channel_write_filter_buf_1_M_real_V;
wire    ap_sync_channel_write_filter_buf_1_M_real_V;
wire    ap_channel_done_filter_buf_0_M_real_V;
wire    Loop_realfft_be_descramble_proc_U0_filter_buf_0_M_real_V_full_n;
reg    ap_sync_reg_channel_write_filter_buf_0_M_real_V;
wire    ap_sync_channel_write_filter_buf_0_M_real_V;
wire    ap_channel_done_filter_buf_1_M_imag_V;
wire    Loop_realfft_be_descramble_proc_U0_filter_buf_1_M_imag_V_full_n;
reg    ap_sync_reg_channel_write_filter_buf_1_M_imag_V;
wire    ap_sync_channel_write_filter_buf_1_M_imag_V;
wire    ap_channel_done_filter_buf_0_M_imag_V;
wire    Loop_realfft_be_descramble_proc_U0_filter_buf_0_M_imag_V_full_n;
reg    ap_sync_reg_channel_write_filter_buf_0_M_imag_V;
wire    ap_sync_channel_write_filter_buf_0_M_imag_V;
wire    Loop_ifft_be_descramble_proc4_U0_ap_start;
wire    Loop_ifft_be_descramble_proc4_U0_ap_done;
wire    Loop_ifft_be_descramble_proc4_U0_ap_continue;
wire    Loop_ifft_be_descramble_proc4_U0_ap_idle;
wire    Loop_ifft_be_descramble_proc4_U0_ap_ready;
wire   [63:0] Loop_ifft_be_descramble_proc4_U0_dout_V_TDATA;
wire    Loop_ifft_be_descramble_proc4_U0_dout_V_TVALID;
wire   [8:0] Loop_ifft_be_descramble_proc4_U0_filter_buf_0_M_imag_V_address0;
wire    Loop_ifft_be_descramble_proc4_U0_filter_buf_0_M_imag_V_ce0;
wire   [8:0] Loop_ifft_be_descramble_proc4_U0_filter_buf_0_M_imag_V_address1;
wire    Loop_ifft_be_descramble_proc4_U0_filter_buf_0_M_imag_V_ce1;
wire   [8:0] Loop_ifft_be_descramble_proc4_U0_filter_buf_1_M_imag_V_address0;
wire    Loop_ifft_be_descramble_proc4_U0_filter_buf_1_M_imag_V_ce0;
wire   [8:0] Loop_ifft_be_descramble_proc4_U0_filter_buf_1_M_imag_V_address1;
wire    Loop_ifft_be_descramble_proc4_U0_filter_buf_1_M_imag_V_ce1;
wire   [8:0] Loop_ifft_be_descramble_proc4_U0_filter_buf_0_M_real_V_address0;
wire    Loop_ifft_be_descramble_proc4_U0_filter_buf_0_M_real_V_ce0;
wire   [8:0] Loop_ifft_be_descramble_proc4_U0_filter_buf_0_M_real_V_address1;
wire    Loop_ifft_be_descramble_proc4_U0_filter_buf_0_M_real_V_ce1;
wire   [8:0] Loop_ifft_be_descramble_proc4_U0_filter_buf_1_M_real_V_address0;
wire    Loop_ifft_be_descramble_proc4_U0_filter_buf_1_M_real_V_ce0;
wire   [8:0] Loop_ifft_be_descramble_proc4_U0_filter_buf_1_M_real_V_address1;
wire    Loop_ifft_be_descramble_proc4_U0_filter_buf_1_M_real_V_ce1;
wire   [9:0] Loop_ifft_be_descramble_proc4_U0_twid_rom_conj_M_real_V_address0;
wire    Loop_ifft_be_descramble_proc4_U0_twid_rom_conj_M_real_V_ce0;
wire   [9:0] Loop_ifft_be_descramble_proc4_U0_twid_rom_conj_M_imag_V_address0;
wire    Loop_ifft_be_descramble_proc4_U0_twid_rom_conj_M_imag_V_ce0;
wire    ap_sync_continue;
wire    twid_rom_M_real_V_i_full_n;
wire    twid_rom_M_real_V_t_empty_n;
wire    twid_rom_M_imag_V_i_full_n;
wire    twid_rom_M_imag_V_t_empty_n;
wire    twid_rom_conj_M_real_V_i_full_n;
wire    twid_rom_conj_M_real_V_t_empty_n;
wire    twid_rom_conj_M_imag_V_i_full_n;
wire    twid_rom_conj_M_imag_V_t_empty_n;
wire    descramble_buf_0_M_imag_V_i_full_n;
wire    descramble_buf_0_M_imag_V_t_empty_n;
wire   [31:0] descramble_buf_0_M_imag_V_t_d1;
wire    descramble_buf_0_M_imag_V_t_we1;
wire    descramble_buf_1_M_imag_V_i_full_n;
wire    descramble_buf_1_M_imag_V_t_empty_n;
wire   [31:0] descramble_buf_1_M_imag_V_t_d1;
wire    descramble_buf_1_M_imag_V_t_we1;
wire    descramble_buf_0_M_real_V_i_full_n;
wire    descramble_buf_0_M_real_V_t_empty_n;
wire   [31:0] descramble_buf_0_M_real_V_t_d1;
wire    descramble_buf_0_M_real_V_t_we1;
wire    descramble_buf_1_M_real_V_i_full_n;
wire    descramble_buf_1_M_real_V_t_empty_n;
wire   [31:0] descramble_buf_1_M_real_V_t_d1;
wire    descramble_buf_1_M_real_V_t_we1;
wire    filter_buf_0_M_imag_V_i_full_n;
wire    filter_buf_0_M_imag_V_t_empty_n;
wire   [30:0] filter_buf_0_M_imag_V_t_d1;
wire    filter_buf_0_M_imag_V_t_we1;
wire    filter_buf_1_M_imag_V_i_full_n;
wire    filter_buf_1_M_imag_V_t_empty_n;
wire   [30:0] filter_buf_1_M_imag_V_t_d1;
wire    filter_buf_1_M_imag_V_t_we1;
wire    filter_buf_0_M_real_V_i_full_n;
wire    filter_buf_0_M_real_V_t_empty_n;
wire   [30:0] filter_buf_0_M_real_V_t_d1;
wire    filter_buf_0_M_real_V_t_we1;
wire    filter_buf_1_M_real_V_i_full_n;
wire    filter_buf_1_M_real_V_t_empty_n;
wire   [30:0] filter_buf_1_M_real_V_t_d1;
wire    filter_buf_1_M_real_V_t_we1;
wire    ap_sync_done;
wire    ap_sync_ready;
reg    ap_sync_reg_Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_ap_ready;
wire    ap_sync_Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_ap_ready;
reg    ap_sync_reg_Loop_realfft_be_buffer_proc3_U0_ap_ready;
wire    ap_sync_Loop_realfft_be_buffer_proc3_U0_ap_ready;
wire    Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_start_full_n;
wire    Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_start_write;
wire    Loop_realfft_be_buffer_proc3_U0_start_full_n;
wire    Loop_realfft_be_buffer_proc3_U0_start_write;
wire    Loop_realfft_be_descramble_proc_U0_start_full_n;
wire    Loop_realfft_be_descramble_proc_U0_start_write;
wire    Loop_ifft_be_descramble_proc4_U0_start_full_n;
wire    Loop_ifft_be_descramble_proc4_U0_start_write;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_channel_write_twid_rom_conj_M_imag_V = 1'b0;
#0 ap_sync_reg_channel_write_twid_rom_conj_M_real_V = 1'b0;
#0 ap_sync_reg_channel_write_twid_rom_M_imag_V = 1'b0;
#0 ap_sync_reg_channel_write_twid_rom_M_real_V = 1'b0;
#0 ap_sync_reg_channel_write_descramble_buf_1_M_real_V = 1'b0;
#0 ap_sync_reg_channel_write_descramble_buf_0_M_real_V = 1'b0;
#0 ap_sync_reg_channel_write_descramble_buf_1_M_imag_V = 1'b0;
#0 ap_sync_reg_channel_write_descramble_buf_0_M_imag_V = 1'b0;
#0 ap_sync_reg_channel_write_filter_buf_1_M_real_V = 1'b0;
#0 ap_sync_reg_channel_write_filter_buf_0_M_real_V = 1'b0;
#0 ap_sync_reg_channel_write_filter_buf_1_M_imag_V = 1'b0;
#0 ap_sync_reg_channel_write_filter_buf_0_M_imag_V = 1'b0;
#0 ap_sync_reg_Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_ap_ready = 1'b0;
#0 ap_sync_reg_Loop_realfft_be_buffer_proc3_U0_ap_ready = 1'b0;
end

hls_xfft2real_descramble_buf_0_M_real_V #(
    .DataWidth( 32 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
descramble_buf_0_M_real_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(Loop_realfft_be_buffer_proc3_U0_descramble_buf_0_M_real_V_address0),
    .i_ce0(Loop_realfft_be_buffer_proc3_U0_descramble_buf_0_M_real_V_ce0),
    .i_we0(Loop_realfft_be_buffer_proc3_U0_descramble_buf_0_M_real_V_we0),
    .i_d0(Loop_realfft_be_buffer_proc3_U0_descramble_buf_0_M_real_V_d0),
    .i_q0(descramble_buf_0_M_real_V_i_q0),
    .i_address1(9'd0),
    .i_ce1(1'b0),
    .i_q1(descramble_buf_0_M_real_V_i_q1),
    .t_address0(Loop_realfft_be_descramble_proc_U0_descramble_buf_0_M_real_V_address0),
    .t_ce0(Loop_realfft_be_descramble_proc_U0_descramble_buf_0_M_real_V_ce0),
    .t_we0(1'b0),
    .t_d0(32'd0),
    .t_q0(descramble_buf_0_M_real_V_t_q0),
    .t_address1(Loop_realfft_be_descramble_proc_U0_descramble_buf_0_M_real_V_address1),
    .t_ce1(Loop_realfft_be_descramble_proc_U0_descramble_buf_0_M_real_V_ce1),
    .t_q1(descramble_buf_0_M_real_V_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(descramble_buf_0_M_real_V_i_full_n),
    .i_write(ap_channel_done_descramble_buf_0_M_real_V),
    .t_empty_n(descramble_buf_0_M_real_V_t_empty_n),
    .t_read(Loop_realfft_be_descramble_proc_U0_ap_ready)
);

hls_xfft2real_descramble_buf_0_M_real_V #(
    .DataWidth( 32 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
descramble_buf_1_M_real_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(Loop_realfft_be_buffer_proc3_U0_descramble_buf_1_M_real_V_address0),
    .i_ce0(Loop_realfft_be_buffer_proc3_U0_descramble_buf_1_M_real_V_ce0),
    .i_we0(Loop_realfft_be_buffer_proc3_U0_descramble_buf_1_M_real_V_we0),
    .i_d0(Loop_realfft_be_buffer_proc3_U0_descramble_buf_1_M_real_V_d0),
    .i_q0(descramble_buf_1_M_real_V_i_q0),
    .i_address1(9'd0),
    .i_ce1(1'b0),
    .i_q1(descramble_buf_1_M_real_V_i_q1),
    .t_address0(Loop_realfft_be_descramble_proc_U0_descramble_buf_1_M_real_V_address0),
    .t_ce0(Loop_realfft_be_descramble_proc_U0_descramble_buf_1_M_real_V_ce0),
    .t_we0(1'b0),
    .t_d0(32'd0),
    .t_q0(descramble_buf_1_M_real_V_t_q0),
    .t_address1(Loop_realfft_be_descramble_proc_U0_descramble_buf_1_M_real_V_address1),
    .t_ce1(Loop_realfft_be_descramble_proc_U0_descramble_buf_1_M_real_V_ce1),
    .t_q1(descramble_buf_1_M_real_V_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(descramble_buf_1_M_real_V_i_full_n),
    .i_write(ap_channel_done_descramble_buf_1_M_real_V),
    .t_empty_n(descramble_buf_1_M_real_V_t_empty_n),
    .t_read(Loop_realfft_be_descramble_proc_U0_ap_ready)
);

hls_xfft2real_descramble_buf_0_M_real_V #(
    .DataWidth( 32 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
descramble_buf_0_M_imag_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(Loop_realfft_be_buffer_proc3_U0_descramble_buf_0_M_imag_V_address0),
    .i_ce0(Loop_realfft_be_buffer_proc3_U0_descramble_buf_0_M_imag_V_ce0),
    .i_we0(Loop_realfft_be_buffer_proc3_U0_descramble_buf_0_M_imag_V_we0),
    .i_d0(Loop_realfft_be_buffer_proc3_U0_descramble_buf_0_M_imag_V_d0),
    .i_q0(descramble_buf_0_M_imag_V_i_q0),
    .i_address1(9'd0),
    .i_ce1(1'b0),
    .i_q1(descramble_buf_0_M_imag_V_i_q1),
    .t_address0(Loop_realfft_be_descramble_proc_U0_descramble_buf_0_M_imag_V_address0),
    .t_ce0(Loop_realfft_be_descramble_proc_U0_descramble_buf_0_M_imag_V_ce0),
    .t_we0(1'b0),
    .t_d0(32'd0),
    .t_q0(descramble_buf_0_M_imag_V_t_q0),
    .t_address1(Loop_realfft_be_descramble_proc_U0_descramble_buf_0_M_imag_V_address1),
    .t_ce1(Loop_realfft_be_descramble_proc_U0_descramble_buf_0_M_imag_V_ce1),
    .t_q1(descramble_buf_0_M_imag_V_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(descramble_buf_0_M_imag_V_i_full_n),
    .i_write(ap_channel_done_descramble_buf_0_M_imag_V),
    .t_empty_n(descramble_buf_0_M_imag_V_t_empty_n),
    .t_read(Loop_realfft_be_descramble_proc_U0_ap_ready)
);

hls_xfft2real_descramble_buf_0_M_real_V #(
    .DataWidth( 32 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
descramble_buf_1_M_imag_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(Loop_realfft_be_buffer_proc3_U0_descramble_buf_1_M_imag_V_address0),
    .i_ce0(Loop_realfft_be_buffer_proc3_U0_descramble_buf_1_M_imag_V_ce0),
    .i_we0(Loop_realfft_be_buffer_proc3_U0_descramble_buf_1_M_imag_V_we0),
    .i_d0(Loop_realfft_be_buffer_proc3_U0_descramble_buf_1_M_imag_V_d0),
    .i_q0(descramble_buf_1_M_imag_V_i_q0),
    .i_address1(9'd0),
    .i_ce1(1'b0),
    .i_q1(descramble_buf_1_M_imag_V_i_q1),
    .t_address0(Loop_realfft_be_descramble_proc_U0_descramble_buf_1_M_imag_V_address0),
    .t_ce0(Loop_realfft_be_descramble_proc_U0_descramble_buf_1_M_imag_V_ce0),
    .t_we0(1'b0),
    .t_d0(32'd0),
    .t_q0(descramble_buf_1_M_imag_V_t_q0),
    .t_address1(Loop_realfft_be_descramble_proc_U0_descramble_buf_1_M_imag_V_address1),
    .t_ce1(Loop_realfft_be_descramble_proc_U0_descramble_buf_1_M_imag_V_ce1),
    .t_q1(descramble_buf_1_M_imag_V_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(descramble_buf_1_M_imag_V_i_full_n),
    .i_write(ap_channel_done_descramble_buf_1_M_imag_V),
    .t_empty_n(descramble_buf_1_M_imag_V_t_empty_n),
    .t_read(Loop_realfft_be_descramble_proc_U0_ap_ready)
);

hls_xfft2real_filter_buf_0_M_real_V #(
    .DataWidth( 31 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
filter_buf_0_M_real_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(Loop_realfft_be_descramble_proc_U0_filter_buf_0_M_real_V_address0),
    .i_ce0(Loop_realfft_be_descramble_proc_U0_filter_buf_0_M_real_V_ce0),
    .i_we0(Loop_realfft_be_descramble_proc_U0_filter_buf_0_M_real_V_we0),
    .i_d0(Loop_realfft_be_descramble_proc_U0_filter_buf_0_M_real_V_d0),
    .i_q0(filter_buf_0_M_real_V_i_q0),
    .i_address1(9'd0),
    .i_ce1(1'b0),
    .i_q1(filter_buf_0_M_real_V_i_q1),
    .t_address0(Loop_ifft_be_descramble_proc4_U0_filter_buf_0_M_real_V_address0),
    .t_ce0(Loop_ifft_be_descramble_proc4_U0_filter_buf_0_M_real_V_ce0),
    .t_we0(1'b0),
    .t_d0(31'd0),
    .t_q0(filter_buf_0_M_real_V_t_q0),
    .t_address1(Loop_ifft_be_descramble_proc4_U0_filter_buf_0_M_real_V_address1),
    .t_ce1(Loop_ifft_be_descramble_proc4_U0_filter_buf_0_M_real_V_ce1),
    .t_q1(filter_buf_0_M_real_V_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(filter_buf_0_M_real_V_i_full_n),
    .i_write(ap_channel_done_filter_buf_0_M_real_V),
    .t_empty_n(filter_buf_0_M_real_V_t_empty_n),
    .t_read(Loop_ifft_be_descramble_proc4_U0_ap_ready)
);

hls_xfft2real_filter_buf_0_M_real_V #(
    .DataWidth( 31 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
filter_buf_1_M_real_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(Loop_realfft_be_descramble_proc_U0_filter_buf_1_M_real_V_address0),
    .i_ce0(Loop_realfft_be_descramble_proc_U0_filter_buf_1_M_real_V_ce0),
    .i_we0(Loop_realfft_be_descramble_proc_U0_filter_buf_1_M_real_V_we0),
    .i_d0(Loop_realfft_be_descramble_proc_U0_filter_buf_1_M_real_V_d0),
    .i_q0(filter_buf_1_M_real_V_i_q0),
    .i_address1(9'd0),
    .i_ce1(1'b0),
    .i_q1(filter_buf_1_M_real_V_i_q1),
    .t_address0(Loop_ifft_be_descramble_proc4_U0_filter_buf_1_M_real_V_address0),
    .t_ce0(Loop_ifft_be_descramble_proc4_U0_filter_buf_1_M_real_V_ce0),
    .t_we0(1'b0),
    .t_d0(31'd0),
    .t_q0(filter_buf_1_M_real_V_t_q0),
    .t_address1(Loop_ifft_be_descramble_proc4_U0_filter_buf_1_M_real_V_address1),
    .t_ce1(Loop_ifft_be_descramble_proc4_U0_filter_buf_1_M_real_V_ce1),
    .t_q1(filter_buf_1_M_real_V_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(filter_buf_1_M_real_V_i_full_n),
    .i_write(ap_channel_done_filter_buf_1_M_real_V),
    .t_empty_n(filter_buf_1_M_real_V_t_empty_n),
    .t_read(Loop_ifft_be_descramble_proc4_U0_ap_ready)
);

hls_xfft2real_filter_buf_0_M_real_V #(
    .DataWidth( 31 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
filter_buf_0_M_imag_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(Loop_realfft_be_descramble_proc_U0_filter_buf_0_M_imag_V_address0),
    .i_ce0(Loop_realfft_be_descramble_proc_U0_filter_buf_0_M_imag_V_ce0),
    .i_we0(Loop_realfft_be_descramble_proc_U0_filter_buf_0_M_imag_V_we0),
    .i_d0(Loop_realfft_be_descramble_proc_U0_filter_buf_0_M_imag_V_d0),
    .i_q0(filter_buf_0_M_imag_V_i_q0),
    .i_address1(9'd0),
    .i_ce1(1'b0),
    .i_q1(filter_buf_0_M_imag_V_i_q1),
    .t_address0(Loop_ifft_be_descramble_proc4_U0_filter_buf_0_M_imag_V_address0),
    .t_ce0(Loop_ifft_be_descramble_proc4_U0_filter_buf_0_M_imag_V_ce0),
    .t_we0(1'b0),
    .t_d0(31'd0),
    .t_q0(filter_buf_0_M_imag_V_t_q0),
    .t_address1(Loop_ifft_be_descramble_proc4_U0_filter_buf_0_M_imag_V_address1),
    .t_ce1(Loop_ifft_be_descramble_proc4_U0_filter_buf_0_M_imag_V_ce1),
    .t_q1(filter_buf_0_M_imag_V_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(filter_buf_0_M_imag_V_i_full_n),
    .i_write(ap_channel_done_filter_buf_0_M_imag_V),
    .t_empty_n(filter_buf_0_M_imag_V_t_empty_n),
    .t_read(Loop_ifft_be_descramble_proc4_U0_ap_ready)
);

hls_xfft2real_filter_buf_0_M_real_V #(
    .DataWidth( 31 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
filter_buf_1_M_imag_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(Loop_realfft_be_descramble_proc_U0_filter_buf_1_M_imag_V_address0),
    .i_ce0(Loop_realfft_be_descramble_proc_U0_filter_buf_1_M_imag_V_ce0),
    .i_we0(Loop_realfft_be_descramble_proc_U0_filter_buf_1_M_imag_V_we0),
    .i_d0(Loop_realfft_be_descramble_proc_U0_filter_buf_1_M_imag_V_d0),
    .i_q0(filter_buf_1_M_imag_V_i_q0),
    .i_address1(9'd0),
    .i_ce1(1'b0),
    .i_q1(filter_buf_1_M_imag_V_i_q1),
    .t_address0(Loop_ifft_be_descramble_proc4_U0_filter_buf_1_M_imag_V_address0),
    .t_ce0(Loop_ifft_be_descramble_proc4_U0_filter_buf_1_M_imag_V_ce0),
    .t_we0(1'b0),
    .t_d0(31'd0),
    .t_q0(filter_buf_1_M_imag_V_t_q0),
    .t_address1(Loop_ifft_be_descramble_proc4_U0_filter_buf_1_M_imag_V_address1),
    .t_ce1(Loop_ifft_be_descramble_proc4_U0_filter_buf_1_M_imag_V_ce1),
    .t_q1(filter_buf_1_M_imag_V_t_q1),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(filter_buf_1_M_imag_V_i_full_n),
    .i_write(ap_channel_done_filter_buf_1_M_imag_V),
    .t_empty_n(filter_buf_1_M_imag_V_t_empty_n),
    .t_read(Loop_ifft_be_descramble_proc4_U0_ap_ready)
);

hls_xfft2real_twid_rom_M_real_V #(
    .DataWidth( 24 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
twid_rom_M_real_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_real_V_address0),
    .i_ce0(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_real_V_ce0),
    .i_we0(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_real_V_we0),
    .i_d0(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_real_V_d0),
    .i_q0(twid_rom_M_real_V_i_q0),
    .i_address1(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_real_V_address1),
    .i_ce1(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_real_V_ce1),
    .i_we1(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_real_V_we1),
    .i_d1(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_real_V_d1),
    .t_address0(Loop_realfft_be_descramble_proc_U0_twid_rom_M_real_V_address0),
    .t_ce0(Loop_realfft_be_descramble_proc_U0_twid_rom_M_real_V_ce0),
    .t_we0(1'b0),
    .t_d0(24'd0),
    .t_q0(twid_rom_M_real_V_t_q0),
    .t_address1(10'd0),
    .t_ce1(1'b0),
    .t_we1(1'b0),
    .t_d1(24'd0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(twid_rom_M_real_V_i_full_n),
    .i_write(ap_channel_done_twid_rom_M_real_V),
    .t_empty_n(twid_rom_M_real_V_t_empty_n),
    .t_read(Loop_realfft_be_descramble_proc_U0_ap_ready)
);

hls_xfft2real_twid_rom_M_real_V #(
    .DataWidth( 24 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
twid_rom_M_imag_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_imag_V_address0),
    .i_ce0(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_imag_V_ce0),
    .i_we0(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_imag_V_we0),
    .i_d0(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_imag_V_d0),
    .i_q0(twid_rom_M_imag_V_i_q0),
    .i_address1(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_imag_V_address1),
    .i_ce1(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_imag_V_ce1),
    .i_we1(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_imag_V_we1),
    .i_d1(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_imag_V_d1),
    .t_address0(Loop_realfft_be_descramble_proc_U0_twid_rom_M_imag_V_address0),
    .t_ce0(Loop_realfft_be_descramble_proc_U0_twid_rom_M_imag_V_ce0),
    .t_we0(1'b0),
    .t_d0(24'd0),
    .t_q0(twid_rom_M_imag_V_t_q0),
    .t_address1(10'd0),
    .t_ce1(1'b0),
    .t_we1(1'b0),
    .t_d1(24'd0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(twid_rom_M_imag_V_i_full_n),
    .i_write(ap_channel_done_twid_rom_M_imag_V),
    .t_empty_n(twid_rom_M_imag_V_t_empty_n),
    .t_read(Loop_realfft_be_descramble_proc_U0_ap_ready)
);

hls_xfft2real_twid_rom_M_real_V #(
    .DataWidth( 24 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
twid_rom_conj_M_real_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_real_V_address0),
    .i_ce0(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_real_V_ce0),
    .i_we0(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_real_V_we0),
    .i_d0(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_real_V_d0),
    .i_q0(twid_rom_conj_M_real_V_i_q0),
    .i_address1(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_real_V_address1),
    .i_ce1(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_real_V_ce1),
    .i_we1(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_real_V_we1),
    .i_d1(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_real_V_d1),
    .t_address0(Loop_ifft_be_descramble_proc4_U0_twid_rom_conj_M_real_V_address0),
    .t_ce0(Loop_ifft_be_descramble_proc4_U0_twid_rom_conj_M_real_V_ce0),
    .t_we0(1'b0),
    .t_d0(24'd0),
    .t_q0(twid_rom_conj_M_real_V_t_q0),
    .t_address1(10'd0),
    .t_ce1(1'b0),
    .t_we1(1'b0),
    .t_d1(24'd0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(twid_rom_conj_M_real_V_i_full_n),
    .i_write(ap_channel_done_twid_rom_conj_M_real_V),
    .t_empty_n(twid_rom_conj_M_real_V_t_empty_n),
    .t_read(Loop_ifft_be_descramble_proc4_U0_ap_ready)
);

hls_xfft2real_twid_rom_conj_M_imag_V #(
    .DataWidth( 23 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
twid_rom_conj_M_imag_V_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .i_address0(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_imag_V_address0),
    .i_ce0(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_imag_V_ce0),
    .i_we0(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_imag_V_we0),
    .i_d0(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_imag_V_d0),
    .i_q0(twid_rom_conj_M_imag_V_i_q0),
    .i_address1(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_imag_V_address1),
    .i_ce1(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_imag_V_ce1),
    .i_we1(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_imag_V_we1),
    .i_d1(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_imag_V_d1),
    .t_address0(Loop_ifft_be_descramble_proc4_U0_twid_rom_conj_M_imag_V_address0),
    .t_ce0(Loop_ifft_be_descramble_proc4_U0_twid_rom_conj_M_imag_V_ce0),
    .t_we0(1'b0),
    .t_d0(23'd0),
    .t_q0(twid_rom_conj_M_imag_V_t_q0),
    .t_address1(10'd0),
    .t_ce1(1'b0),
    .t_we1(1'b0),
    .t_d1(23'd0),
    .i_ce(1'b1),
    .t_ce(1'b1),
    .i_full_n(twid_rom_conj_M_imag_V_i_full_n),
    .i_write(ap_channel_done_twid_rom_conj_M_imag_V),
    .t_empty_n(twid_rom_conj_M_imag_V_t_empty_n),
    .t_read(Loop_ifft_be_descramble_proc4_U0_ap_ready)
);

hls_xfft2real_Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_ap_start),
    .ap_done(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_ap_done),
    .ap_continue(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_ap_continue),
    .ap_idle(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_ap_idle),
    .ap_ready(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_ap_ready),
    .twid_rom_M_real_V_address0(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_real_V_address0),
    .twid_rom_M_real_V_ce0(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_real_V_ce0),
    .twid_rom_M_real_V_we0(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_real_V_we0),
    .twid_rom_M_real_V_d0(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_real_V_d0),
    .twid_rom_M_real_V_address1(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_real_V_address1),
    .twid_rom_M_real_V_ce1(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_real_V_ce1),
    .twid_rom_M_real_V_we1(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_real_V_we1),
    .twid_rom_M_real_V_d1(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_real_V_d1),
    .twid_rom_M_imag_V_address0(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_imag_V_address0),
    .twid_rom_M_imag_V_ce0(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_imag_V_ce0),
    .twid_rom_M_imag_V_we0(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_imag_V_we0),
    .twid_rom_M_imag_V_d0(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_imag_V_d0),
    .twid_rom_M_imag_V_address1(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_imag_V_address1),
    .twid_rom_M_imag_V_ce1(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_imag_V_ce1),
    .twid_rom_M_imag_V_we1(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_imag_V_we1),
    .twid_rom_M_imag_V_d1(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_imag_V_d1),
    .twid_rom_conj_M_real_V_address0(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_real_V_address0),
    .twid_rom_conj_M_real_V_ce0(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_real_V_ce0),
    .twid_rom_conj_M_real_V_we0(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_real_V_we0),
    .twid_rom_conj_M_real_V_d0(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_real_V_d0),
    .twid_rom_conj_M_real_V_address1(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_real_V_address1),
    .twid_rom_conj_M_real_V_ce1(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_real_V_ce1),
    .twid_rom_conj_M_real_V_we1(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_real_V_we1),
    .twid_rom_conj_M_real_V_d1(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_real_V_d1),
    .twid_rom_conj_M_imag_V_address0(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_imag_V_address0),
    .twid_rom_conj_M_imag_V_ce0(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_imag_V_ce0),
    .twid_rom_conj_M_imag_V_we0(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_imag_V_we0),
    .twid_rom_conj_M_imag_V_d0(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_imag_V_d0),
    .twid_rom_conj_M_imag_V_address1(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_imag_V_address1),
    .twid_rom_conj_M_imag_V_ce1(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_imag_V_ce1),
    .twid_rom_conj_M_imag_V_we1(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_imag_V_we1),
    .twid_rom_conj_M_imag_V_d1(Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_imag_V_d1)
);

hls_xfft2real_Loop_realfft_be_buffer_proc3 Loop_realfft_be_buffer_proc3_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_realfft_be_buffer_proc3_U0_ap_start),
    .ap_done(Loop_realfft_be_buffer_proc3_U0_ap_done),
    .ap_continue(Loop_realfft_be_buffer_proc3_U0_ap_continue),
    .ap_idle(Loop_realfft_be_buffer_proc3_U0_ap_idle),
    .ap_ready(Loop_realfft_be_buffer_proc3_U0_ap_ready),
    .descramble_buf_0_M_imag_V_address0(Loop_realfft_be_buffer_proc3_U0_descramble_buf_0_M_imag_V_address0),
    .descramble_buf_0_M_imag_V_ce0(Loop_realfft_be_buffer_proc3_U0_descramble_buf_0_M_imag_V_ce0),
    .descramble_buf_0_M_imag_V_we0(Loop_realfft_be_buffer_proc3_U0_descramble_buf_0_M_imag_V_we0),
    .descramble_buf_0_M_imag_V_d0(Loop_realfft_be_buffer_proc3_U0_descramble_buf_0_M_imag_V_d0),
    .descramble_buf_1_M_imag_V_address0(Loop_realfft_be_buffer_proc3_U0_descramble_buf_1_M_imag_V_address0),
    .descramble_buf_1_M_imag_V_ce0(Loop_realfft_be_buffer_proc3_U0_descramble_buf_1_M_imag_V_ce0),
    .descramble_buf_1_M_imag_V_we0(Loop_realfft_be_buffer_proc3_U0_descramble_buf_1_M_imag_V_we0),
    .descramble_buf_1_M_imag_V_d0(Loop_realfft_be_buffer_proc3_U0_descramble_buf_1_M_imag_V_d0),
    .din_V_TDATA(din_V_TDATA),
    .din_V_TVALID(din_V_TVALID),
    .din_V_TREADY(Loop_realfft_be_buffer_proc3_U0_din_V_TREADY),
    .descramble_buf_0_M_real_V_address0(Loop_realfft_be_buffer_proc3_U0_descramble_buf_0_M_real_V_address0),
    .descramble_buf_0_M_real_V_ce0(Loop_realfft_be_buffer_proc3_U0_descramble_buf_0_M_real_V_ce0),
    .descramble_buf_0_M_real_V_we0(Loop_realfft_be_buffer_proc3_U0_descramble_buf_0_M_real_V_we0),
    .descramble_buf_0_M_real_V_d0(Loop_realfft_be_buffer_proc3_U0_descramble_buf_0_M_real_V_d0),
    .descramble_buf_1_M_real_V_address0(Loop_realfft_be_buffer_proc3_U0_descramble_buf_1_M_real_V_address0),
    .descramble_buf_1_M_real_V_ce0(Loop_realfft_be_buffer_proc3_U0_descramble_buf_1_M_real_V_ce0),
    .descramble_buf_1_M_real_V_we0(Loop_realfft_be_buffer_proc3_U0_descramble_buf_1_M_real_V_we0),
    .descramble_buf_1_M_real_V_d0(Loop_realfft_be_buffer_proc3_U0_descramble_buf_1_M_real_V_d0)
);

hls_xfft2real_Loop_realfft_be_descramble_proc Loop_realfft_be_descramble_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_realfft_be_descramble_proc_U0_ap_start),
    .ap_done(Loop_realfft_be_descramble_proc_U0_ap_done),
    .ap_continue(Loop_realfft_be_descramble_proc_U0_ap_continue),
    .ap_idle(Loop_realfft_be_descramble_proc_U0_ap_idle),
    .ap_ready(Loop_realfft_be_descramble_proc_U0_ap_ready),
    .filter_buf_0_M_imag_V_address0(Loop_realfft_be_descramble_proc_U0_filter_buf_0_M_imag_V_address0),
    .filter_buf_0_M_imag_V_ce0(Loop_realfft_be_descramble_proc_U0_filter_buf_0_M_imag_V_ce0),
    .filter_buf_0_M_imag_V_we0(Loop_realfft_be_descramble_proc_U0_filter_buf_0_M_imag_V_we0),
    .filter_buf_0_M_imag_V_d0(Loop_realfft_be_descramble_proc_U0_filter_buf_0_M_imag_V_d0),
    .filter_buf_1_M_imag_V_address0(Loop_realfft_be_descramble_proc_U0_filter_buf_1_M_imag_V_address0),
    .filter_buf_1_M_imag_V_ce0(Loop_realfft_be_descramble_proc_U0_filter_buf_1_M_imag_V_ce0),
    .filter_buf_1_M_imag_V_we0(Loop_realfft_be_descramble_proc_U0_filter_buf_1_M_imag_V_we0),
    .filter_buf_1_M_imag_V_d0(Loop_realfft_be_descramble_proc_U0_filter_buf_1_M_imag_V_d0),
    .filter_buf_0_M_real_V_address0(Loop_realfft_be_descramble_proc_U0_filter_buf_0_M_real_V_address0),
    .filter_buf_0_M_real_V_ce0(Loop_realfft_be_descramble_proc_U0_filter_buf_0_M_real_V_ce0),
    .filter_buf_0_M_real_V_we0(Loop_realfft_be_descramble_proc_U0_filter_buf_0_M_real_V_we0),
    .filter_buf_0_M_real_V_d0(Loop_realfft_be_descramble_proc_U0_filter_buf_0_M_real_V_d0),
    .filter_buf_1_M_real_V_address0(Loop_realfft_be_descramble_proc_U0_filter_buf_1_M_real_V_address0),
    .filter_buf_1_M_real_V_ce0(Loop_realfft_be_descramble_proc_U0_filter_buf_1_M_real_V_ce0),
    .filter_buf_1_M_real_V_we0(Loop_realfft_be_descramble_proc_U0_filter_buf_1_M_real_V_we0),
    .filter_buf_1_M_real_V_d0(Loop_realfft_be_descramble_proc_U0_filter_buf_1_M_real_V_d0),
    .descramble_buf_0_M_imag_V_address0(Loop_realfft_be_descramble_proc_U0_descramble_buf_0_M_imag_V_address0),
    .descramble_buf_0_M_imag_V_ce0(Loop_realfft_be_descramble_proc_U0_descramble_buf_0_M_imag_V_ce0),
    .descramble_buf_0_M_imag_V_q0(descramble_buf_0_M_imag_V_t_q0),
    .descramble_buf_0_M_imag_V_address1(Loop_realfft_be_descramble_proc_U0_descramble_buf_0_M_imag_V_address1),
    .descramble_buf_0_M_imag_V_ce1(Loop_realfft_be_descramble_proc_U0_descramble_buf_0_M_imag_V_ce1),
    .descramble_buf_0_M_imag_V_q1(descramble_buf_0_M_imag_V_t_q1),
    .descramble_buf_1_M_imag_V_address0(Loop_realfft_be_descramble_proc_U0_descramble_buf_1_M_imag_V_address0),
    .descramble_buf_1_M_imag_V_ce0(Loop_realfft_be_descramble_proc_U0_descramble_buf_1_M_imag_V_ce0),
    .descramble_buf_1_M_imag_V_q0(descramble_buf_1_M_imag_V_t_q0),
    .descramble_buf_1_M_imag_V_address1(Loop_realfft_be_descramble_proc_U0_descramble_buf_1_M_imag_V_address1),
    .descramble_buf_1_M_imag_V_ce1(Loop_realfft_be_descramble_proc_U0_descramble_buf_1_M_imag_V_ce1),
    .descramble_buf_1_M_imag_V_q1(descramble_buf_1_M_imag_V_t_q1),
    .descramble_buf_0_M_real_V_address0(Loop_realfft_be_descramble_proc_U0_descramble_buf_0_M_real_V_address0),
    .descramble_buf_0_M_real_V_ce0(Loop_realfft_be_descramble_proc_U0_descramble_buf_0_M_real_V_ce0),
    .descramble_buf_0_M_real_V_q0(descramble_buf_0_M_real_V_t_q0),
    .descramble_buf_0_M_real_V_address1(Loop_realfft_be_descramble_proc_U0_descramble_buf_0_M_real_V_address1),
    .descramble_buf_0_M_real_V_ce1(Loop_realfft_be_descramble_proc_U0_descramble_buf_0_M_real_V_ce1),
    .descramble_buf_0_M_real_V_q1(descramble_buf_0_M_real_V_t_q1),
    .descramble_buf_1_M_real_V_address0(Loop_realfft_be_descramble_proc_U0_descramble_buf_1_M_real_V_address0),
    .descramble_buf_1_M_real_V_ce0(Loop_realfft_be_descramble_proc_U0_descramble_buf_1_M_real_V_ce0),
    .descramble_buf_1_M_real_V_q0(descramble_buf_1_M_real_V_t_q0),
    .descramble_buf_1_M_real_V_address1(Loop_realfft_be_descramble_proc_U0_descramble_buf_1_M_real_V_address1),
    .descramble_buf_1_M_real_V_ce1(Loop_realfft_be_descramble_proc_U0_descramble_buf_1_M_real_V_ce1),
    .descramble_buf_1_M_real_V_q1(descramble_buf_1_M_real_V_t_q1),
    .twid_rom_M_real_V_address0(Loop_realfft_be_descramble_proc_U0_twid_rom_M_real_V_address0),
    .twid_rom_M_real_V_ce0(Loop_realfft_be_descramble_proc_U0_twid_rom_M_real_V_ce0),
    .twid_rom_M_real_V_q0(twid_rom_M_real_V_t_q0),
    .twid_rom_M_imag_V_address0(Loop_realfft_be_descramble_proc_U0_twid_rom_M_imag_V_address0),
    .twid_rom_M_imag_V_ce0(Loop_realfft_be_descramble_proc_U0_twid_rom_M_imag_V_ce0),
    .twid_rom_M_imag_V_q0(twid_rom_M_imag_V_t_q0)
);

hls_xfft2real_Loop_ifft_be_descramble_proc4 Loop_ifft_be_descramble_proc4_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_ifft_be_descramble_proc4_U0_ap_start),
    .ap_done(Loop_ifft_be_descramble_proc4_U0_ap_done),
    .ap_continue(Loop_ifft_be_descramble_proc4_U0_ap_continue),
    .ap_idle(Loop_ifft_be_descramble_proc4_U0_ap_idle),
    .ap_ready(Loop_ifft_be_descramble_proc4_U0_ap_ready),
    .dout_V_TDATA(Loop_ifft_be_descramble_proc4_U0_dout_V_TDATA),
    .dout_V_TVALID(Loop_ifft_be_descramble_proc4_U0_dout_V_TVALID),
    .dout_V_TREADY(dout_V_TREADY),
    .filter_buf_0_M_imag_V_address0(Loop_ifft_be_descramble_proc4_U0_filter_buf_0_M_imag_V_address0),
    .filter_buf_0_M_imag_V_ce0(Loop_ifft_be_descramble_proc4_U0_filter_buf_0_M_imag_V_ce0),
    .filter_buf_0_M_imag_V_q0(filter_buf_0_M_imag_V_t_q0),
    .filter_buf_0_M_imag_V_address1(Loop_ifft_be_descramble_proc4_U0_filter_buf_0_M_imag_V_address1),
    .filter_buf_0_M_imag_V_ce1(Loop_ifft_be_descramble_proc4_U0_filter_buf_0_M_imag_V_ce1),
    .filter_buf_0_M_imag_V_q1(filter_buf_0_M_imag_V_t_q1),
    .filter_buf_1_M_imag_V_address0(Loop_ifft_be_descramble_proc4_U0_filter_buf_1_M_imag_V_address0),
    .filter_buf_1_M_imag_V_ce0(Loop_ifft_be_descramble_proc4_U0_filter_buf_1_M_imag_V_ce0),
    .filter_buf_1_M_imag_V_q0(filter_buf_1_M_imag_V_t_q0),
    .filter_buf_1_M_imag_V_address1(Loop_ifft_be_descramble_proc4_U0_filter_buf_1_M_imag_V_address1),
    .filter_buf_1_M_imag_V_ce1(Loop_ifft_be_descramble_proc4_U0_filter_buf_1_M_imag_V_ce1),
    .filter_buf_1_M_imag_V_q1(filter_buf_1_M_imag_V_t_q1),
    .filter_buf_0_M_real_V_address0(Loop_ifft_be_descramble_proc4_U0_filter_buf_0_M_real_V_address0),
    .filter_buf_0_M_real_V_ce0(Loop_ifft_be_descramble_proc4_U0_filter_buf_0_M_real_V_ce0),
    .filter_buf_0_M_real_V_q0(filter_buf_0_M_real_V_t_q0),
    .filter_buf_0_M_real_V_address1(Loop_ifft_be_descramble_proc4_U0_filter_buf_0_M_real_V_address1),
    .filter_buf_0_M_real_V_ce1(Loop_ifft_be_descramble_proc4_U0_filter_buf_0_M_real_V_ce1),
    .filter_buf_0_M_real_V_q1(filter_buf_0_M_real_V_t_q1),
    .filter_buf_1_M_real_V_address0(Loop_ifft_be_descramble_proc4_U0_filter_buf_1_M_real_V_address0),
    .filter_buf_1_M_real_V_ce0(Loop_ifft_be_descramble_proc4_U0_filter_buf_1_M_real_V_ce0),
    .filter_buf_1_M_real_V_q0(filter_buf_1_M_real_V_t_q0),
    .filter_buf_1_M_real_V_address1(Loop_ifft_be_descramble_proc4_U0_filter_buf_1_M_real_V_address1),
    .filter_buf_1_M_real_V_ce1(Loop_ifft_be_descramble_proc4_U0_filter_buf_1_M_real_V_ce1),
    .filter_buf_1_M_real_V_q1(filter_buf_1_M_real_V_t_q1),
    .twid_rom_conj_M_real_V_address0(Loop_ifft_be_descramble_proc4_U0_twid_rom_conj_M_real_V_address0),
    .twid_rom_conj_M_real_V_ce0(Loop_ifft_be_descramble_proc4_U0_twid_rom_conj_M_real_V_ce0),
    .twid_rom_conj_M_real_V_q0(twid_rom_conj_M_real_V_t_q0),
    .twid_rom_conj_M_imag_V_address0(Loop_ifft_be_descramble_proc4_U0_twid_rom_conj_M_imag_V_address0),
    .twid_rom_conj_M_imag_V_ce0(Loop_ifft_be_descramble_proc4_U0_twid_rom_conj_M_imag_V_ce0),
    .twid_rom_conj_M_imag_V_q0(twid_rom_conj_M_imag_V_t_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_ap_ready <= ap_sync_Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_Loop_realfft_be_buffer_proc3_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_Loop_realfft_be_buffer_proc3_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_Loop_realfft_be_buffer_proc3_U0_ap_ready <= ap_sync_Loop_realfft_be_buffer_proc3_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_descramble_buf_0_M_imag_V <= 1'b0;
    end else begin
        if (((Loop_realfft_be_buffer_proc3_U0_ap_done & Loop_realfft_be_buffer_proc3_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_descramble_buf_0_M_imag_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_descramble_buf_0_M_imag_V <= ap_sync_channel_write_descramble_buf_0_M_imag_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_descramble_buf_0_M_real_V <= 1'b0;
    end else begin
        if (((Loop_realfft_be_buffer_proc3_U0_ap_done & Loop_realfft_be_buffer_proc3_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_descramble_buf_0_M_real_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_descramble_buf_0_M_real_V <= ap_sync_channel_write_descramble_buf_0_M_real_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_descramble_buf_1_M_imag_V <= 1'b0;
    end else begin
        if (((Loop_realfft_be_buffer_proc3_U0_ap_done & Loop_realfft_be_buffer_proc3_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_descramble_buf_1_M_imag_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_descramble_buf_1_M_imag_V <= ap_sync_channel_write_descramble_buf_1_M_imag_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_descramble_buf_1_M_real_V <= 1'b0;
    end else begin
        if (((Loop_realfft_be_buffer_proc3_U0_ap_done & Loop_realfft_be_buffer_proc3_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_descramble_buf_1_M_real_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_descramble_buf_1_M_real_V <= ap_sync_channel_write_descramble_buf_1_M_real_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_filter_buf_0_M_imag_V <= 1'b0;
    end else begin
        if (((Loop_realfft_be_descramble_proc_U0_ap_done & Loop_realfft_be_descramble_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_filter_buf_0_M_imag_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_filter_buf_0_M_imag_V <= ap_sync_channel_write_filter_buf_0_M_imag_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_filter_buf_0_M_real_V <= 1'b0;
    end else begin
        if (((Loop_realfft_be_descramble_proc_U0_ap_done & Loop_realfft_be_descramble_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_filter_buf_0_M_real_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_filter_buf_0_M_real_V <= ap_sync_channel_write_filter_buf_0_M_real_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_filter_buf_1_M_imag_V <= 1'b0;
    end else begin
        if (((Loop_realfft_be_descramble_proc_U0_ap_done & Loop_realfft_be_descramble_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_filter_buf_1_M_imag_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_filter_buf_1_M_imag_V <= ap_sync_channel_write_filter_buf_1_M_imag_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_filter_buf_1_M_real_V <= 1'b0;
    end else begin
        if (((Loop_realfft_be_descramble_proc_U0_ap_done & Loop_realfft_be_descramble_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_filter_buf_1_M_real_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_filter_buf_1_M_real_V <= ap_sync_channel_write_filter_buf_1_M_real_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_twid_rom_M_imag_V <= 1'b0;
    end else begin
        if (((Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_ap_done & Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_twid_rom_M_imag_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_twid_rom_M_imag_V <= ap_sync_channel_write_twid_rom_M_imag_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_twid_rom_M_real_V <= 1'b0;
    end else begin
        if (((Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_ap_done & Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_twid_rom_M_real_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_twid_rom_M_real_V <= ap_sync_channel_write_twid_rom_M_real_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_twid_rom_conj_M_imag_V <= 1'b0;
    end else begin
        if (((Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_ap_done & Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_twid_rom_conj_M_imag_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_twid_rom_conj_M_imag_V <= ap_sync_channel_write_twid_rom_conj_M_imag_V;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_channel_write_twid_rom_conj_M_real_V <= 1'b0;
    end else begin
        if (((Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_ap_done & Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_ap_continue) == 1'b1)) begin
            ap_sync_reg_channel_write_twid_rom_conj_M_real_V <= 1'b0;
        end else begin
            ap_sync_reg_channel_write_twid_rom_conj_M_real_V <= ap_sync_channel_write_twid_rom_conj_M_real_V;
        end
    end
end

assign Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_ap_continue = (ap_sync_channel_write_twid_rom_conj_M_real_V & ap_sync_channel_write_twid_rom_conj_M_imag_V & ap_sync_channel_write_twid_rom_M_real_V & ap_sync_channel_write_twid_rom_M_imag_V);

assign Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_ap_start = ((ap_sync_reg_Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_start_full_n = 1'b1;

assign Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_start_write = 1'b0;

assign Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_imag_V_full_n = twid_rom_M_imag_V_i_full_n;

assign Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_real_V_full_n = twid_rom_M_real_V_i_full_n;

assign Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_imag_V_full_n = twid_rom_conj_M_imag_V_i_full_n;

assign Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_real_V_full_n = twid_rom_conj_M_real_V_i_full_n;

assign Loop_ifft_be_descramble_proc4_U0_ap_continue = 1'b1;

assign Loop_ifft_be_descramble_proc4_U0_ap_start = (twid_rom_conj_M_real_V_t_empty_n & twid_rom_conj_M_imag_V_t_empty_n & filter_buf_1_M_real_V_t_empty_n & filter_buf_1_M_imag_V_t_empty_n & filter_buf_0_M_real_V_t_empty_n & filter_buf_0_M_imag_V_t_empty_n);

assign Loop_ifft_be_descramble_proc4_U0_start_full_n = 1'b1;

assign Loop_ifft_be_descramble_proc4_U0_start_write = 1'b0;

assign Loop_realfft_be_buffer_proc3_U0_ap_continue = (ap_sync_channel_write_descramble_buf_1_M_real_V & ap_sync_channel_write_descramble_buf_1_M_imag_V & ap_sync_channel_write_descramble_buf_0_M_real_V & ap_sync_channel_write_descramble_buf_0_M_imag_V);

assign Loop_realfft_be_buffer_proc3_U0_ap_start = ((ap_sync_reg_Loop_realfft_be_buffer_proc3_U0_ap_ready ^ 1'b1) & ap_start);

assign Loop_realfft_be_buffer_proc3_U0_descramble_buf_0_M_imag_V_full_n = descramble_buf_0_M_imag_V_i_full_n;

assign Loop_realfft_be_buffer_proc3_U0_descramble_buf_0_M_real_V_full_n = descramble_buf_0_M_real_V_i_full_n;

assign Loop_realfft_be_buffer_proc3_U0_descramble_buf_1_M_imag_V_full_n = descramble_buf_1_M_imag_V_i_full_n;

assign Loop_realfft_be_buffer_proc3_U0_descramble_buf_1_M_real_V_full_n = descramble_buf_1_M_real_V_i_full_n;

assign Loop_realfft_be_buffer_proc3_U0_start_full_n = 1'b1;

assign Loop_realfft_be_buffer_proc3_U0_start_write = 1'b0;

assign Loop_realfft_be_descramble_proc_U0_ap_continue = (ap_sync_channel_write_filter_buf_1_M_real_V & ap_sync_channel_write_filter_buf_1_M_imag_V & ap_sync_channel_write_filter_buf_0_M_real_V & ap_sync_channel_write_filter_buf_0_M_imag_V);

assign Loop_realfft_be_descramble_proc_U0_ap_start = (twid_rom_M_real_V_t_empty_n & twid_rom_M_imag_V_t_empty_n & descramble_buf_1_M_real_V_t_empty_n & descramble_buf_1_M_imag_V_t_empty_n & descramble_buf_0_M_real_V_t_empty_n & descramble_buf_0_M_imag_V_t_empty_n);

assign Loop_realfft_be_descramble_proc_U0_filter_buf_0_M_imag_V_full_n = filter_buf_0_M_imag_V_i_full_n;

assign Loop_realfft_be_descramble_proc_U0_filter_buf_0_M_real_V_full_n = filter_buf_0_M_real_V_i_full_n;

assign Loop_realfft_be_descramble_proc_U0_filter_buf_1_M_imag_V_full_n = filter_buf_1_M_imag_V_i_full_n;

assign Loop_realfft_be_descramble_proc_U0_filter_buf_1_M_real_V_full_n = filter_buf_1_M_real_V_i_full_n;

assign Loop_realfft_be_descramble_proc_U0_start_full_n = 1'b1;

assign Loop_realfft_be_descramble_proc_U0_start_write = 1'b0;

assign ap_channel_done_descramble_buf_0_M_imag_V = ((ap_sync_reg_channel_write_descramble_buf_0_M_imag_V ^ 1'b1) & Loop_realfft_be_buffer_proc3_U0_ap_done);

assign ap_channel_done_descramble_buf_0_M_real_V = ((ap_sync_reg_channel_write_descramble_buf_0_M_real_V ^ 1'b1) & Loop_realfft_be_buffer_proc3_U0_ap_done);

assign ap_channel_done_descramble_buf_1_M_imag_V = ((ap_sync_reg_channel_write_descramble_buf_1_M_imag_V ^ 1'b1) & Loop_realfft_be_buffer_proc3_U0_ap_done);

assign ap_channel_done_descramble_buf_1_M_real_V = ((ap_sync_reg_channel_write_descramble_buf_1_M_real_V ^ 1'b1) & Loop_realfft_be_buffer_proc3_U0_ap_done);

assign ap_channel_done_filter_buf_0_M_imag_V = ((ap_sync_reg_channel_write_filter_buf_0_M_imag_V ^ 1'b1) & Loop_realfft_be_descramble_proc_U0_ap_done);

assign ap_channel_done_filter_buf_0_M_real_V = ((ap_sync_reg_channel_write_filter_buf_0_M_real_V ^ 1'b1) & Loop_realfft_be_descramble_proc_U0_ap_done);

assign ap_channel_done_filter_buf_1_M_imag_V = ((ap_sync_reg_channel_write_filter_buf_1_M_imag_V ^ 1'b1) & Loop_realfft_be_descramble_proc_U0_ap_done);

assign ap_channel_done_filter_buf_1_M_real_V = ((ap_sync_reg_channel_write_filter_buf_1_M_real_V ^ 1'b1) & Loop_realfft_be_descramble_proc_U0_ap_done);

assign ap_channel_done_twid_rom_M_imag_V = ((ap_sync_reg_channel_write_twid_rom_M_imag_V ^ 1'b1) & Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_ap_done);

assign ap_channel_done_twid_rom_M_real_V = ((ap_sync_reg_channel_write_twid_rom_M_real_V ^ 1'b1) & Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_ap_done);

assign ap_channel_done_twid_rom_conj_M_imag_V = ((ap_sync_reg_channel_write_twid_rom_conj_M_imag_V ^ 1'b1) & Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_ap_done);

assign ap_channel_done_twid_rom_conj_M_real_V = ((ap_sync_reg_channel_write_twid_rom_conj_M_real_V ^ 1'b1) & Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_ap_done);

assign ap_done = Loop_ifft_be_descramble_proc4_U0_ap_done;

assign ap_idle = ((filter_buf_1_M_real_V_t_empty_n ^ 1'b1) & (filter_buf_0_M_real_V_t_empty_n ^ 1'b1) & (filter_buf_1_M_imag_V_t_empty_n ^ 1'b1) & (filter_buf_0_M_imag_V_t_empty_n ^ 1'b1) & (descramble_buf_1_M_real_V_t_empty_n ^ 1'b1) & (descramble_buf_0_M_real_V_t_empty_n ^ 1'b1) & (descramble_buf_1_M_imag_V_t_empty_n ^ 1'b1) & (descramble_buf_0_M_imag_V_t_empty_n ^ 1'b1) & (twid_rom_conj_M_imag_V_t_empty_n ^ 1'b1) & (twid_rom_conj_M_real_V_t_empty_n ^ 1'b1) & (twid_rom_M_imag_V_t_empty_n ^ 1'b1) & (twid_rom_M_real_V_t_empty_n ^ 1'b1) & Loop_realfft_be_descramble_proc_U0_ap_idle & Loop_realfft_be_buffer_proc3_U0_ap_idle & Loop_ifft_be_descramble_proc4_U0_ap_idle & Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_ap_idle);

assign ap_ready = ap_sync_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_ap_ready = (ap_sync_reg_Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_ap_ready | Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_ap_ready);

assign ap_sync_Loop_realfft_be_buffer_proc3_U0_ap_ready = (ap_sync_reg_Loop_realfft_be_buffer_proc3_U0_ap_ready | Loop_realfft_be_buffer_proc3_U0_ap_ready);

assign ap_sync_channel_write_descramble_buf_0_M_imag_V = ((ap_channel_done_descramble_buf_0_M_imag_V & Loop_realfft_be_buffer_proc3_U0_descramble_buf_0_M_imag_V_full_n) | ap_sync_reg_channel_write_descramble_buf_0_M_imag_V);

assign ap_sync_channel_write_descramble_buf_0_M_real_V = ((ap_channel_done_descramble_buf_0_M_real_V & Loop_realfft_be_buffer_proc3_U0_descramble_buf_0_M_real_V_full_n) | ap_sync_reg_channel_write_descramble_buf_0_M_real_V);

assign ap_sync_channel_write_descramble_buf_1_M_imag_V = ((ap_channel_done_descramble_buf_1_M_imag_V & Loop_realfft_be_buffer_proc3_U0_descramble_buf_1_M_imag_V_full_n) | ap_sync_reg_channel_write_descramble_buf_1_M_imag_V);

assign ap_sync_channel_write_descramble_buf_1_M_real_V = ((ap_channel_done_descramble_buf_1_M_real_V & Loop_realfft_be_buffer_proc3_U0_descramble_buf_1_M_real_V_full_n) | ap_sync_reg_channel_write_descramble_buf_1_M_real_V);

assign ap_sync_channel_write_filter_buf_0_M_imag_V = ((ap_channel_done_filter_buf_0_M_imag_V & Loop_realfft_be_descramble_proc_U0_filter_buf_0_M_imag_V_full_n) | ap_sync_reg_channel_write_filter_buf_0_M_imag_V);

assign ap_sync_channel_write_filter_buf_0_M_real_V = ((ap_channel_done_filter_buf_0_M_real_V & Loop_realfft_be_descramble_proc_U0_filter_buf_0_M_real_V_full_n) | ap_sync_reg_channel_write_filter_buf_0_M_real_V);

assign ap_sync_channel_write_filter_buf_1_M_imag_V = ((ap_channel_done_filter_buf_1_M_imag_V & Loop_realfft_be_descramble_proc_U0_filter_buf_1_M_imag_V_full_n) | ap_sync_reg_channel_write_filter_buf_1_M_imag_V);

assign ap_sync_channel_write_filter_buf_1_M_real_V = ((ap_channel_done_filter_buf_1_M_real_V & Loop_realfft_be_descramble_proc_U0_filter_buf_1_M_real_V_full_n) | ap_sync_reg_channel_write_filter_buf_1_M_real_V);

assign ap_sync_channel_write_twid_rom_M_imag_V = ((ap_channel_done_twid_rom_M_imag_V & Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_imag_V_full_n) | ap_sync_reg_channel_write_twid_rom_M_imag_V);

assign ap_sync_channel_write_twid_rom_M_real_V = ((ap_channel_done_twid_rom_M_real_V & Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_M_real_V_full_n) | ap_sync_reg_channel_write_twid_rom_M_real_V);

assign ap_sync_channel_write_twid_rom_conj_M_imag_V = ((ap_channel_done_twid_rom_conj_M_imag_V & Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_imag_V_full_n) | ap_sync_reg_channel_write_twid_rom_conj_M_imag_V);

assign ap_sync_channel_write_twid_rom_conj_M_real_V = ((ap_channel_done_twid_rom_conj_M_real_V & Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_twid_rom_conj_M_real_V_full_n) | ap_sync_reg_channel_write_twid_rom_conj_M_real_V);

assign ap_sync_continue = 1'b1;

assign ap_sync_done = Loop_ifft_be_descramble_proc4_U0_ap_done;

assign ap_sync_ready = (ap_sync_Loop_realfft_be_buffer_proc3_U0_ap_ready & ap_sync_Block_ZN8ap_fixedILi24ELi1EL9ap_q_mode5EL9ap_o_mode0ELi0EEC2Ei_exit_i205_proc_U0_ap_ready);

assign descramble_buf_0_M_imag_V_t_d1 = 32'd0;

assign descramble_buf_0_M_imag_V_t_we1 = 1'b0;

assign descramble_buf_0_M_real_V_t_d1 = 32'd0;

assign descramble_buf_0_M_real_V_t_we1 = 1'b0;

assign descramble_buf_1_M_imag_V_t_d1 = 32'd0;

assign descramble_buf_1_M_imag_V_t_we1 = 1'b0;

assign descramble_buf_1_M_real_V_t_d1 = 32'd0;

assign descramble_buf_1_M_real_V_t_we1 = 1'b0;

assign din_V_TREADY = Loop_realfft_be_buffer_proc3_U0_din_V_TREADY;

assign dout_V_TDATA = Loop_ifft_be_descramble_proc4_U0_dout_V_TDATA;

assign dout_V_TVALID = Loop_ifft_be_descramble_proc4_U0_dout_V_TVALID;

assign filter_buf_0_M_imag_V_t_d1 = 31'd0;

assign filter_buf_0_M_imag_V_t_we1 = 1'b0;

assign filter_buf_0_M_real_V_t_d1 = 31'd0;

assign filter_buf_0_M_real_V_t_we1 = 1'b0;

assign filter_buf_1_M_imag_V_t_d1 = 31'd0;

assign filter_buf_1_M_imag_V_t_we1 = 1'b0;

assign filter_buf_1_M_real_V_t_d1 = 31'd0;

assign filter_buf_1_M_real_V_t_we1 = 1'b0;


// synthesis translate_off
`include "hls_xfft2real_hls_deadlock_detector.vh"
// synthesis translate_on

endmodule //hls_xfft2real

