// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module hls_xfft2real_xfft2real_complex_ap_fixed_32_1_5_3_0_complex_ap_fixed_32_1_5_3_0_11_true_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        din_V_TDATA,
        din_V_TVALID,
        din_V_TREADY,
        dout_V_TDATA,
        dout_V_TVALID,
        dout_V_TREADY
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_pp1_stage0 = 7'd8;
parameter    ap_ST_fsm_state15 = 7'd16;
parameter    ap_ST_fsm_pp2_stage0 = 7'd32;
parameter    ap_ST_fsm_state24 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [63:0] din_V_TDATA;
input   din_V_TVALID;
output   din_V_TREADY;
output  [63:0] dout_V_TDATA;
output   dout_V_TVALID;
input   dout_V_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [9:0] twid_rom_M_real_V_address0;
reg    twid_rom_M_real_V_ce0;
wire   [23:0] twid_rom_M_real_V_q0;
wire   [9:0] twid_rom_M_imag_V_address0;
reg    twid_rom_M_imag_V_ce0;
wire   [23:0] twid_rom_M_imag_V_q0;
wire   [9:0] filter_rom_address0;
reg    filter_rom_ce0;
wire   [22:0] filter_rom_q0;
wire   [9:0] twid_rom_conj_M_real_V_address0;
reg    twid_rom_conj_M_real_V_ce0;
wire   [23:0] twid_rom_conj_M_real_V_q0;
wire   [9:0] twid_rom_conj_M_imag_V_address0;
reg    twid_rom_conj_M_imag_V_ce0;
wire   [22:0] twid_rom_conj_M_imag_V_q0;
reg    din_V_TDATA_blk_n;
wire    ap_CS_fsm_state2;
reg    dout_V_TDATA_blk_n;
reg    ap_enable_reg_pp2_iter6;
wire    ap_block_pp2_stage0;
reg   [0:0] icmp_ln117_reg_1883;
reg   [0:0] icmp_ln117_reg_1883_pp2_iter5_reg;
reg    ap_enable_reg_pp2_iter7;
reg   [0:0] icmp_ln117_reg_1883_pp2_iter6_reg;
reg   [10:0] i_1_reg_467;
reg   [10:0] i_2_reg_479;
wire   [9:0] i_fu_491_p2;
wire   [10:0] add_ln95_fu_547_p2;
reg   [10:0] add_ln95_reg_1614;
wire    ap_CS_fsm_pp1_stage0;
reg    ap_enable_reg_pp1_iter0;
wire    ap_block_state4_pp1_stage0_iter0;
wire    ap_block_state5_pp1_stage0_iter1;
wire    ap_block_state6_pp1_stage0_iter2;
wire    ap_block_state7_pp1_stage0_iter3;
wire    ap_block_state8_pp1_stage0_iter4;
wire    ap_block_state9_pp1_stage0_iter5;
wire    ap_block_state10_pp1_stage0_iter6;
wire    ap_block_state11_pp1_stage0_iter7;
wire    ap_block_state12_pp1_stage0_iter8;
wire    ap_block_state13_pp1_stage0_iter9;
wire    ap_block_state14_pp1_stage0_iter10;
wire    ap_block_pp1_stage0_11001;
wire   [0:0] icmp_ln95_fu_553_p2;
reg   [0:0] icmp_ln95_reg_1619;
reg   [0:0] tmp_4_reg_1653;
reg   [8:0] filter_buf_0_M_real_V_addr_2_reg_1669;
reg   [8:0] filter_buf_0_M_real_V_addr_2_reg_1669_pp1_iter1_reg;
reg   [8:0] filter_buf_0_M_real_V_addr_2_reg_1669_pp1_iter2_reg;
reg   [8:0] filter_buf_0_M_real_V_addr_2_reg_1669_pp1_iter3_reg;
reg   [8:0] filter_buf_0_M_real_V_addr_2_reg_1669_pp1_iter4_reg;
reg   [8:0] filter_buf_0_M_real_V_addr_2_reg_1669_pp1_iter5_reg;
reg   [8:0] filter_buf_0_M_real_V_addr_2_reg_1669_pp1_iter6_reg;
reg   [8:0] filter_buf_0_M_real_V_addr_2_reg_1669_pp1_iter7_reg;
reg   [8:0] filter_buf_0_M_real_V_addr_2_reg_1669_pp1_iter8_reg;
reg   [8:0] filter_buf_0_M_real_V_addr_2_reg_1669_pp1_iter9_reg;
reg   [8:0] filter_buf_1_M_real_V_addr_2_reg_1674;
reg   [8:0] filter_buf_1_M_real_V_addr_2_reg_1674_pp1_iter1_reg;
reg   [8:0] filter_buf_1_M_real_V_addr_2_reg_1674_pp1_iter2_reg;
reg   [8:0] filter_buf_1_M_real_V_addr_2_reg_1674_pp1_iter3_reg;
reg   [8:0] filter_buf_1_M_real_V_addr_2_reg_1674_pp1_iter4_reg;
reg   [8:0] filter_buf_1_M_real_V_addr_2_reg_1674_pp1_iter5_reg;
reg   [8:0] filter_buf_1_M_real_V_addr_2_reg_1674_pp1_iter6_reg;
reg   [8:0] filter_buf_1_M_real_V_addr_2_reg_1674_pp1_iter7_reg;
reg   [8:0] filter_buf_1_M_real_V_addr_2_reg_1674_pp1_iter8_reg;
reg   [8:0] filter_buf_1_M_real_V_addr_2_reg_1674_pp1_iter9_reg;
reg   [8:0] filter_buf_0_M_imag_V_addr_2_reg_1679;
reg   [8:0] filter_buf_0_M_imag_V_addr_2_reg_1679_pp1_iter1_reg;
reg   [8:0] filter_buf_0_M_imag_V_addr_2_reg_1679_pp1_iter2_reg;
reg   [8:0] filter_buf_0_M_imag_V_addr_2_reg_1679_pp1_iter3_reg;
reg   [8:0] filter_buf_0_M_imag_V_addr_2_reg_1679_pp1_iter4_reg;
reg   [8:0] filter_buf_0_M_imag_V_addr_2_reg_1679_pp1_iter5_reg;
reg   [8:0] filter_buf_0_M_imag_V_addr_2_reg_1679_pp1_iter6_reg;
reg   [8:0] filter_buf_0_M_imag_V_addr_2_reg_1679_pp1_iter7_reg;
reg   [8:0] filter_buf_0_M_imag_V_addr_2_reg_1679_pp1_iter8_reg;
reg   [8:0] filter_buf_0_M_imag_V_addr_2_reg_1679_pp1_iter9_reg;
reg   [8:0] filter_buf_1_M_imag_V_addr_2_reg_1684;
reg   [8:0] filter_buf_1_M_imag_V_addr_2_reg_1684_pp1_iter1_reg;
reg   [8:0] filter_buf_1_M_imag_V_addr_2_reg_1684_pp1_iter2_reg;
reg   [8:0] filter_buf_1_M_imag_V_addr_2_reg_1684_pp1_iter3_reg;
reg   [8:0] filter_buf_1_M_imag_V_addr_2_reg_1684_pp1_iter4_reg;
reg   [8:0] filter_buf_1_M_imag_V_addr_2_reg_1684_pp1_iter5_reg;
reg   [8:0] filter_buf_1_M_imag_V_addr_2_reg_1684_pp1_iter6_reg;
reg   [8:0] filter_buf_1_M_imag_V_addr_2_reg_1684_pp1_iter7_reg;
reg   [8:0] filter_buf_1_M_imag_V_addr_2_reg_1684_pp1_iter8_reg;
reg   [8:0] filter_buf_1_M_imag_V_addr_2_reg_1684_pp1_iter9_reg;
wire   [0:0] icmp_ln97_fu_622_p2;
reg   [0:0] icmp_ln97_reg_1689;
reg   [0:0] icmp_ln97_reg_1689_pp1_iter2_reg;
reg   [0:0] icmp_ln97_reg_1689_pp1_iter3_reg;
reg   [0:0] icmp_ln97_reg_1689_pp1_iter4_reg;
reg   [0:0] icmp_ln97_reg_1689_pp1_iter5_reg;
reg   [0:0] icmp_ln97_reg_1689_pp1_iter6_reg;
reg   [0:0] icmp_ln97_reg_1689_pp1_iter7_reg;
reg   [0:0] icmp_ln97_reg_1689_pp1_iter8_reg;
reg   [0:0] icmp_ln97_reg_1689_pp1_iter9_reg;
wire  signed [31:0] y1_M_real_fu_628_p3;
reg  signed [31:0] y1_M_real_reg_1693;
reg  signed [31:0] y1_M_real_reg_1693_pp1_iter2_reg;
reg  signed [31:0] y1_M_real_reg_1693_pp1_iter3_reg;
reg  signed [31:0] y1_M_real_reg_1693_pp1_iter4_reg;
reg  signed [31:0] y1_M_real_reg_1693_pp1_iter5_reg;
wire  signed [31:0] y1_M_imag_fu_636_p3;
reg  signed [31:0] y1_M_imag_reg_1699;
reg  signed [31:0] y1_M_imag_reg_1699_pp1_iter2_reg;
reg  signed [31:0] y1_M_imag_reg_1699_pp1_iter3_reg;
reg  signed [31:0] y1_M_imag_reg_1699_pp1_iter4_reg;
reg  signed [31:0] y1_M_imag_reg_1699_pp1_iter5_reg;
wire   [0:0] icmp_ln100_fu_644_p2;
reg   [0:0] icmp_ln100_reg_1706;
reg   [0:0] icmp_ln100_reg_1706_pp1_iter2_reg;
reg   [0:0] icmp_ln100_reg_1706_pp1_iter3_reg;
reg   [0:0] icmp_ln100_reg_1706_pp1_iter4_reg;
reg   [0:0] icmp_ln100_reg_1706_pp1_iter5_reg;
wire   [31:0] rhs_6_fu_661_p2;
reg   [31:0] rhs_6_reg_1712;
wire   [32:0] ret_V_14_fu_678_p2;
reg   [32:0] ret_V_14_reg_1717;
reg   [32:0] ret_V_14_reg_1717_pp1_iter2_reg;
reg   [32:0] ret_V_14_reg_1717_pp1_iter3_reg;
reg   [32:0] ret_V_14_reg_1717_pp1_iter4_reg;
reg   [32:0] ret_V_14_reg_1717_pp1_iter5_reg;
wire   [32:0] ret_V_16_fu_684_p2;
reg   [32:0] ret_V_16_reg_1724;
reg   [0:0] tmp_8_reg_1729;
reg   [31:0] trunc_ln1148_11_reg_1734;
wire   [32:0] ret_V_15_fu_714_p2;
reg   [32:0] ret_V_15_reg_1754;
reg   [32:0] ret_V_15_reg_1754_pp1_iter3_reg;
reg   [32:0] ret_V_15_reg_1754_pp1_iter4_reg;
reg   [32:0] ret_V_15_reg_1754_pp1_iter5_reg;
wire   [31:0] g_M_real_V_fu_766_p3;
reg   [31:0] g_M_real_V_reg_1761;
wire   [31:0] g_M_imag_V_fu_795_p3;
reg   [31:0] g_M_imag_V_reg_1766;
reg   [23:0] twid_rom_M_real_V_load_reg_1771;
reg   [23:0] twid_rom_M_imag_V_load_reg_1776;
reg   [22:0] filter_rom_load_reg_1781;
reg   [22:0] filter_rom_load_reg_1781_pp1_iter3_reg;
reg   [22:0] filter_rom_load_reg_1781_pp1_iter4_reg;
reg   [22:0] filter_rom_load_reg_1781_pp1_iter5_reg;
reg   [22:0] filter_rom_load_reg_1781_pp1_iter6_reg;
wire  signed [62:0] sext_ln1115_fu_815_p1;
wire  signed [62:0] sext_ln1118_fu_819_p1;
wire  signed [62:0] sext_ln1115_1_fu_828_p1;
wire  signed [62:0] sext_ln1118_1_fu_832_p1;
reg   [31:0] trunc_ln1148_7_reg_1810;
reg   [31:0] trunc_ln1148_s_reg_1815;
wire   [62:0] grp_fu_822_p2;
reg   [62:0] r_V_1_reg_1820;
wire   [62:0] grp_fu_835_p2;
reg   [62:0] r_V_3_reg_1825;
wire   [62:0] grp_fu_841_p2;
reg   [62:0] r_V_4_reg_1830;
wire   [62:0] grp_fu_847_p2;
reg   [62:0] r_V_5_reg_1835;
wire   [31:0] cdata_M_imag_V_3_fu_989_p3;
reg  signed [31:0] cdata_M_imag_V_3_reg_1840;
wire   [31:0] cdata_M_real_V_3_fu_996_p3;
reg  signed [31:0] cdata_M_real_V_3_reg_1845;
wire   [62:0] zext_ln1118_fu_1013_p1;
reg   [31:0] p_r_V_3_reg_1866;
reg   [31:0] p_r_M_imag_V_reg_1872;
wire   [10:0] add_ln117_fu_1052_p2;
reg   [10:0] add_ln117_reg_1878;
wire    ap_CS_fsm_pp2_stage0;
reg    ap_enable_reg_pp2_iter0;
wire    ap_block_state16_pp2_stage0_iter0;
wire    ap_block_state17_pp2_stage0_iter1;
wire    ap_block_state18_pp2_stage0_iter2;
wire    ap_block_state19_pp2_stage0_iter3;
wire    ap_block_state20_pp2_stage0_iter4;
wire    ap_block_state21_pp2_stage0_iter5;
reg    ap_block_state22_pp2_stage0_iter6;
reg    ap_block_state22_io;
reg    ap_block_state23_pp2_stage0_iter7;
reg    ap_block_state23_io;
reg    ap_block_pp2_stage0_11001;
wire   [0:0] icmp_ln117_fu_1058_p2;
reg   [0:0] icmp_ln117_reg_1883_pp2_iter1_reg;
reg   [0:0] icmp_ln117_reg_1883_pp2_iter2_reg;
reg   [0:0] icmp_ln117_reg_1883_pp2_iter3_reg;
reg   [0:0] icmp_ln117_reg_1883_pp2_iter4_reg;
reg   [0:0] tmp_12_reg_1917;
wire   [31:0] rhs_7_fu_1136_p3;
reg   [31:0] rhs_7_reg_1933;
wire   [0:0] icmp_ln121_fu_1144_p2;
reg   [0:0] icmp_ln121_reg_1938;
reg   [0:0] icmp_ln121_reg_1938_pp2_iter2_reg;
reg   [0:0] icmp_ln121_reg_1938_pp2_iter3_reg;
reg   [0:0] icmp_ln121_reg_1938_pp2_iter4_reg;
reg   [0:0] icmp_ln121_reg_1938_pp2_iter5_reg;
wire  signed [32:0] sext_ln703_1_fu_1150_p1;
reg  signed [32:0] sext_ln703_1_reg_1943;
reg  signed [32:0] sext_ln703_1_reg_1943_pp2_iter2_reg;
reg  signed [32:0] sext_ln703_1_reg_1943_pp2_iter3_reg;
reg  signed [32:0] sext_ln703_1_reg_1943_pp2_iter4_reg;
wire   [31:0] rhs_5_fu_1161_p2;
reg   [31:0] rhs_5_reg_1949;
wire   [32:0] ret_V_19_fu_1178_p2;
reg   [32:0] ret_V_19_reg_1954;
reg   [32:0] ret_V_19_reg_1954_pp2_iter2_reg;
reg   [32:0] ret_V_19_reg_1954_pp2_iter3_reg;
reg   [32:0] ret_V_19_reg_1954_pp2_iter4_reg;
reg   [32:0] ret_V_19_reg_1954_pp2_iter5_reg;
wire   [32:0] ret_V_21_fu_1184_p2;
reg   [32:0] ret_V_21_reg_1961;
reg   [0:0] tmp_16_reg_1966;
reg   [31:0] trunc_ln1148_19_reg_1971;
wire  signed [32:0] sext_ln703_2_fu_1208_p1;
reg  signed [32:0] sext_ln703_2_reg_1986;
reg  signed [32:0] sext_ln703_2_reg_1986_pp2_iter3_reg;
reg  signed [32:0] sext_ln703_2_reg_1986_pp2_iter4_reg;
wire   [32:0] ret_V_20_fu_1214_p2;
reg   [32:0] ret_V_20_reg_1992;
reg   [32:0] ret_V_20_reg_1992_pp2_iter3_reg;
reg   [32:0] ret_V_20_reg_1992_pp2_iter4_reg;
reg   [32:0] ret_V_20_reg_1992_pp2_iter5_reg;
wire   [31:0] g_M_real_V_1_fu_1266_p3;
reg   [31:0] g_M_real_V_1_reg_1999;
wire   [31:0] g_M_imag_V_1_fu_1295_p3;
reg   [31:0] g_M_imag_V_1_reg_2004;
reg   [23:0] twid_rom_conj_M_real_V_load_reg_2009;
reg   [22:0] twid_rom_conj_M_imag_V_load_reg_2014;
wire  signed [62:0] sext_ln1115_4_fu_1315_p1;
wire  signed [62:0] sext_ln1118_2_fu_1319_p1;
wire   [62:0] zext_ln1115_fu_1328_p1;
wire  signed [62:0] sext_ln1118_3_fu_1332_p1;
wire   [32:0] ret_V_17_fu_1353_p2;
reg   [32:0] ret_V_17_reg_2043;
wire   [32:0] ret_V_18_fu_1357_p2;
reg   [32:0] ret_V_18_reg_2050;
reg   [31:0] trunc_ln1148_12_reg_2057;
reg   [31:0] trunc_ln1148_14_reg_2062;
wire   [62:0] grp_fu_1322_p2;
reg   [62:0] r_V_12_reg_2067;
wire   [62:0] grp_fu_1335_p2;
reg   [62:0] r_V_13_reg_2072;
wire   [62:0] grp_fu_1341_p2;
reg   [62:0] r_V_14_reg_2077;
wire   [62:0] grp_fu_1347_p2;
reg   [62:0] r_V_15_reg_2082;
wire    ap_CS_fsm_state3;
wire    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_exit_iter0_state4;
reg    ap_enable_reg_pp1_iter1;
reg    ap_enable_reg_pp1_iter2;
reg    ap_enable_reg_pp1_iter3;
reg    ap_enable_reg_pp1_iter4;
reg    ap_enable_reg_pp1_iter5;
reg    ap_enable_reg_pp1_iter6;
reg    ap_enable_reg_pp1_iter7;
reg    ap_enable_reg_pp1_iter8;
reg    ap_enable_reg_pp1_iter9;
reg    ap_enable_reg_pp1_iter10;
wire    ap_CS_fsm_state15;
reg    ap_block_pp2_stage0_subdone;
reg    ap_condition_pp2_exit_iter0_state16;
reg    ap_enable_reg_pp2_iter1;
reg    ap_enable_reg_pp2_iter2;
reg    ap_enable_reg_pp2_iter3;
reg    ap_enable_reg_pp2_iter4;
reg    ap_enable_reg_pp2_iter5;
reg   [8:0] descramble_buf_0_M_real_V_address0;
reg    descramble_buf_0_M_real_V_ce0;
reg    descramble_buf_0_M_real_V_we0;
wire   [31:0] descramble_buf_0_M_real_V_q0;
wire   [8:0] descramble_buf_0_M_real_V_address1;
reg    descramble_buf_0_M_real_V_ce1;
wire   [31:0] descramble_buf_0_M_real_V_q1;
reg   [8:0] descramble_buf_1_M_real_V_address0;
reg    descramble_buf_1_M_real_V_ce0;
reg    descramble_buf_1_M_real_V_we0;
wire   [31:0] descramble_buf_1_M_real_V_q0;
wire   [8:0] descramble_buf_1_M_real_V_address1;
reg    descramble_buf_1_M_real_V_ce1;
wire   [31:0] descramble_buf_1_M_real_V_q1;
reg   [8:0] descramble_buf_0_M_imag_V_address0;
reg    descramble_buf_0_M_imag_V_ce0;
reg    descramble_buf_0_M_imag_V_we0;
wire   [31:0] descramble_buf_0_M_imag_V_d0;
wire   [31:0] descramble_buf_0_M_imag_V_q0;
wire   [8:0] descramble_buf_0_M_imag_V_address1;
reg    descramble_buf_0_M_imag_V_ce1;
wire   [31:0] descramble_buf_0_M_imag_V_q1;
reg   [8:0] descramble_buf_1_M_imag_V_address0;
reg    descramble_buf_1_M_imag_V_ce0;
reg    descramble_buf_1_M_imag_V_we0;
wire   [31:0] descramble_buf_1_M_imag_V_d0;
wire   [31:0] descramble_buf_1_M_imag_V_q0;
wire   [8:0] descramble_buf_1_M_imag_V_address1;
reg    descramble_buf_1_M_imag_V_ce1;
wire   [31:0] descramble_buf_1_M_imag_V_q1;
reg   [8:0] filter_buf_0_M_real_V_address0;
reg    filter_buf_0_M_real_V_ce0;
reg    filter_buf_0_M_real_V_we0;
wire   [31:0] filter_buf_0_M_real_V_q0;
wire   [8:0] filter_buf_0_M_real_V_address1;
reg    filter_buf_0_M_real_V_ce1;
wire   [31:0] filter_buf_0_M_real_V_q1;
reg   [8:0] filter_buf_1_M_real_V_address0;
reg    filter_buf_1_M_real_V_ce0;
reg    filter_buf_1_M_real_V_we0;
wire   [31:0] filter_buf_1_M_real_V_q0;
wire   [8:0] filter_buf_1_M_real_V_address1;
reg    filter_buf_1_M_real_V_ce1;
wire   [31:0] filter_buf_1_M_real_V_q1;
reg   [8:0] filter_buf_0_M_imag_V_address0;
reg    filter_buf_0_M_imag_V_ce0;
reg    filter_buf_0_M_imag_V_we0;
wire   [31:0] filter_buf_0_M_imag_V_q0;
wire   [8:0] filter_buf_0_M_imag_V_address1;
reg    filter_buf_0_M_imag_V_ce1;
wire   [31:0] filter_buf_0_M_imag_V_q1;
reg   [8:0] filter_buf_1_M_imag_V_address0;
reg    filter_buf_1_M_imag_V_ce0;
reg    filter_buf_1_M_imag_V_we0;
wire   [31:0] filter_buf_1_M_imag_V_q0;
wire   [8:0] filter_buf_1_M_imag_V_address1;
reg    filter_buf_1_M_imag_V_ce1;
wire   [31:0] filter_buf_1_M_imag_V_q1;
reg   [9:0] i_3171_reg_456;
reg    ap_block_state1;
wire   [0:0] icmp_ln86_fu_541_p2;
reg   [10:0] ap_phi_mux_i_1_phi_fu_471_p4;
wire    ap_block_pp1_stage0;
reg   [10:0] ap_phi_mux_i_2_phi_fu_483_p4;
wire   [63:0] zext_ln92_fu_525_p1;
wire   [63:0] zext_ln97_fu_567_p1;
wire   [63:0] zext_ln703_fu_589_p1;
wire   [63:0] zext_ln95_fu_605_p1;
wire   [63:0] zext_ln119_fu_1072_p1;
wire   [63:0] zext_ln703_1_fu_1090_p1;
wire   [63:0] zext_ln117_fu_1106_p1;
reg    ap_block_pp2_stage0_01001;
wire   [0:0] tmp_2_fu_533_p3;
wire   [31:0] trunc_ln145_fu_497_p1;
reg   [8:0] trunc_ln1_fu_515_p4;
wire   [8:0] trunc_ln97_fu_563_p1;
wire   [9:0] trunc_ln95_fu_559_p1;
wire   [9:0] sub_ln703_fu_579_p2;
wire   [8:0] trunc_ln703_fu_585_p1;
wire   [1:0] tmp_3_fu_612_p4;
wire   [31:0] select_ln703_fu_654_p3;
wire   [31:0] rhs_fu_667_p3;
wire  signed [32:0] sext_ln703_3_fu_674_p1;
wire  signed [32:0] sext_ln703_fu_650_p1;
wire  signed [32:0] sext_ln703_5_fu_711_p1;
wire  signed [32:0] sext_ln703_4_fu_708_p1;
wire   [32:0] ret_V_fu_720_p2;
wire   [31:0] trunc_ln1148_6_fu_740_p4;
wire   [32:0] sub_ln1148_8_fu_734_p2;
wire   [0:0] tmp_7_fu_726_p3;
wire   [31:0] trunc_ln1148_9_fu_756_p4;
wire   [31:0] sub_ln1148_9_fu_750_p2;
wire   [32:0] sub_ln1148_10_fu_774_p2;
wire   [31:0] trunc_ln1148_10_fu_779_p4;
wire   [31:0] sub_ln1148_11_fu_789_p2;
wire   [31:0] r_V_fu_801_p3;
wire  signed [31:0] grp_fu_822_p0;
wire  signed [31:0] grp_fu_822_p1;
wire   [31:0] r_V_2_fu_808_p3;
wire  signed [31:0] grp_fu_835_p0;
wire  signed [31:0] grp_fu_835_p1;
wire  signed [31:0] grp_fu_841_p0;
wire  signed [31:0] grp_fu_841_p1;
wire  signed [31:0] grp_fu_847_p0;
wire  signed [31:0] grp_fu_847_p1;
wire   [32:0] sub_ln1148_4_fu_853_p2;
wire   [32:0] sub_ln1148_6_fu_868_p2;
wire   [0:0] tmp_5_fu_891_p3;
wire   [31:0] sub_ln1148_5_fu_898_p2;
wire   [31:0] trunc_ln1148_8_fu_903_p4;
wire   [0:0] tmp_6_fu_920_p3;
wire   [31:0] sub_ln1148_7_fu_927_p2;
wire   [31:0] trunc_ln1148_3_fu_932_p4;
wire   [62:0] ret_V_4_fu_949_p2;
wire   [62:0] ret_V_5_fu_963_p2;
wire   [31:0] p_r_V_fu_953_p4;
wire   [31:0] f_M_real_V_fu_912_p3;
wire   [31:0] trunc_ln5_fu_967_p4;
wire   [31:0] f_M_imag_V_fu_941_p3;
wire   [31:0] cdata_M_imag_V_fu_887_p2;
wire   [31:0] p_r_M_imag_V_6_fu_983_p2;
wire   [31:0] cdata_M_real_V_fu_883_p2;
wire   [31:0] p_r_M_real_V_fu_977_p2;
wire   [30:0] shl_ln_fu_1003_p3;
wire   [30:0] grp_fu_1017_p1;
wire   [30:0] grp_fu_1026_p1;
wire   [62:0] grp_fu_1017_p2;
wire   [62:0] grp_fu_1026_p2;
wire   [8:0] trunc_ln119_fu_1068_p1;
wire   [9:0] trunc_ln117_fu_1064_p1;
wire   [9:0] sub_ln703_2_fu_1080_p2;
wire   [8:0] trunc_ln703_1_fu_1086_p1;
wire   [1:0] tmp_9_fu_1112_p4;
wire   [0:0] icmp_ln119_fu_1122_p2;
wire   [31:0] lhs_V_fu_1128_p3;
wire   [31:0] select_ln703_2_fu_1154_p3;
wire   [31:0] rhs_4_fu_1167_p3;
wire  signed [32:0] sext_ln703_6_fu_1174_p1;
wire  signed [32:0] sext_ln703_7_fu_1211_p1;
wire   [32:0] ret_V_10_fu_1220_p2;
wire   [31:0] trunc_ln1148_16_fu_1240_p4;
wire   [32:0] sub_ln1148_16_fu_1234_p2;
wire   [0:0] tmp_15_fu_1226_p3;
wire   [31:0] trunc_ln1148_17_fu_1256_p4;
wire   [31:0] sub_ln1148_17_fu_1250_p2;
wire   [32:0] sub_ln1148_18_fu_1274_p2;
wire   [31:0] trunc_ln1148_18_fu_1279_p4;
wire   [31:0] sub_ln1148_19_fu_1289_p2;
wire   [31:0] r_V_11_fu_1301_p3;
wire  signed [31:0] grp_fu_1322_p0;
wire  signed [31:0] grp_fu_1322_p1;
wire   [30:0] r_V_10_fu_1308_p3;
wire  signed [31:0] grp_fu_1335_p0;
wire   [30:0] grp_fu_1335_p1;
wire  signed [31:0] grp_fu_1341_p0;
wire  signed [31:0] grp_fu_1341_p1;
wire  signed [31:0] grp_fu_1347_p0;
wire   [30:0] grp_fu_1347_p1;
wire   [32:0] sub_ln1148_12_fu_1361_p2;
wire   [32:0] sub_ln1148_14_fu_1376_p2;
wire   [32:0] sub_ln1148_fu_1398_p2;
wire   [31:0] trunc_ln1148_1_fu_1403_p4;
wire   [0:0] tmp_10_fu_1391_p3;
wire   [31:0] sub_ln1148_1_fu_1413_p2;
wire   [31:0] trunc_ln1148_2_fu_1419_p4;
wire   [32:0] sub_ln1148_2_fu_1443_p2;
wire   [31:0] trunc_ln1148_4_fu_1448_p4;
wire   [0:0] tmp_11_fu_1436_p3;
wire   [31:0] sub_ln1148_3_fu_1458_p2;
wire   [31:0] trunc_ln1148_5_fu_1464_p4;
wire   [31:0] select_ln1148_1_fu_1473_p3;
wire   [31:0] select_ln1148_fu_1428_p3;
wire   [0:0] tmp_13_fu_1489_p3;
wire   [31:0] sub_ln1148_13_fu_1496_p2;
wire   [31:0] trunc_ln1148_13_fu_1501_p4;
wire   [0:0] tmp_14_fu_1518_p3;
wire   [31:0] sub_ln1148_15_fu_1525_p2;
wire   [31:0] trunc_ln1148_15_fu_1530_p4;
wire   [62:0] ret_V_12_fu_1547_p2;
wire   [62:0] ret_V_13_fu_1561_p2;
wire   [31:0] p_r_V_2_fu_1551_p4;
wire   [31:0] f_M_real_V_1_fu_1510_p3;
wire   [31:0] trunc_ln708_3_fu_1565_p4;
wire   [31:0] f_M_imag_V_1_fu_1539_p3;
wire   [31:0] p_r_M_imag_V_5_fu_1581_p2;
wire   [31:0] p_r_M_real_V_6_fu_1575_p2;
wire   [63:0] tmp_fu_1481_p3;
wire   [63:0] tmp_1_fu_1587_p3;
reg    grp_fu_1322_ce;
reg    grp_fu_1335_ce;
reg    grp_fu_1341_ce;
reg    grp_fu_1347_ce;
wire    ap_CS_fsm_state24;
wire    regslice_both_dout_V_U_apdone_blk;
reg   [6:0] ap_NS_fsm;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
reg    ap_idle_pp2;
wire    ap_enable_pp2;
wire    regslice_both_din_V_U_apdone_blk;
wire   [63:0] din_V_TDATA_int_regslice;
wire    din_V_TVALID_int_regslice;
reg    din_V_TREADY_int_regslice;
wire    regslice_both_din_V_U_ack_in;
wire   [63:0] dout_V_TDATA_int_regslice;
reg    dout_V_TVALID_int_regslice;
wire    dout_V_TREADY_int_regslice;
wire    regslice_both_dout_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 7'd1;
#0 ap_enable_reg_pp2_iter6 = 1'b0;
#0 ap_enable_reg_pp2_iter7 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp2_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter2 = 1'b0;
#0 ap_enable_reg_pp1_iter3 = 1'b0;
#0 ap_enable_reg_pp1_iter4 = 1'b0;
#0 ap_enable_reg_pp1_iter5 = 1'b0;
#0 ap_enable_reg_pp1_iter6 = 1'b0;
#0 ap_enable_reg_pp1_iter7 = 1'b0;
#0 ap_enable_reg_pp1_iter8 = 1'b0;
#0 ap_enable_reg_pp1_iter9 = 1'b0;
#0 ap_enable_reg_pp1_iter10 = 1'b0;
#0 ap_enable_reg_pp2_iter1 = 1'b0;
#0 ap_enable_reg_pp2_iter2 = 1'b0;
#0 ap_enable_reg_pp2_iter3 = 1'b0;
#0 ap_enable_reg_pp2_iter4 = 1'b0;
#0 ap_enable_reg_pp2_iter5 = 1'b0;
end

hls_xfft2real_xfft2real_complex_ap_fixed_32_1_5_3_0_complex_ap_fixed_32_1_5_3_0_11_true_s_tbkb #(
    .DataWidth( 24 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
twid_rom_M_real_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(twid_rom_M_real_V_address0),
    .ce0(twid_rom_M_real_V_ce0),
    .q0(twid_rom_M_real_V_q0)
);

hls_xfft2real_xfft2real_complex_ap_fixed_32_1_5_3_0_complex_ap_fixed_32_1_5_3_0_11_true_s_tcud #(
    .DataWidth( 24 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
twid_rom_M_imag_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(twid_rom_M_imag_V_address0),
    .ce0(twid_rom_M_imag_V_ce0),
    .q0(twid_rom_M_imag_V_q0)
);

hls_xfft2real_xfft2real_complex_ap_fixed_32_1_5_3_0_complex_ap_fixed_32_1_5_3_0_11_true_s_fdEe #(
    .DataWidth( 23 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
filter_rom_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(filter_rom_address0),
    .ce0(filter_rom_ce0),
    .q0(filter_rom_q0)
);

hls_xfft2real_xfft2real_complex_ap_fixed_32_1_5_3_0_complex_ap_fixed_32_1_5_3_0_11_true_s_tbkb #(
    .DataWidth( 24 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
twid_rom_conj_M_real_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(twid_rom_conj_M_real_V_address0),
    .ce0(twid_rom_conj_M_real_V_ce0),
    .q0(twid_rom_conj_M_real_V_q0)
);

hls_xfft2real_xfft2real_complex_ap_fixed_32_1_5_3_0_complex_ap_fixed_32_1_5_3_0_11_true_s_tfYi #(
    .DataWidth( 23 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
twid_rom_conj_M_imag_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(twid_rom_conj_M_imag_V_address0),
    .ce0(twid_rom_conj_M_imag_V_ce0),
    .q0(twid_rom_conj_M_imag_V_q0)
);

hls_xfft2real_xfft2real_complex_ap_fixed_32_1_5_3_0_complex_ap_fixed_32_1_5_3_0_11_true_s_dg8j #(
    .DataWidth( 32 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
descramble_buf_0_M_real_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(descramble_buf_0_M_real_V_address0),
    .ce0(descramble_buf_0_M_real_V_ce0),
    .we0(descramble_buf_0_M_real_V_we0),
    .d0(trunc_ln145_fu_497_p1),
    .q0(descramble_buf_0_M_real_V_q0),
    .address1(descramble_buf_0_M_real_V_address1),
    .ce1(descramble_buf_0_M_real_V_ce1),
    .q1(descramble_buf_0_M_real_V_q1)
);

hls_xfft2real_xfft2real_complex_ap_fixed_32_1_5_3_0_complex_ap_fixed_32_1_5_3_0_11_true_s_dg8j #(
    .DataWidth( 32 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
descramble_buf_1_M_real_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(descramble_buf_1_M_real_V_address0),
    .ce0(descramble_buf_1_M_real_V_ce0),
    .we0(descramble_buf_1_M_real_V_we0),
    .d0(trunc_ln145_fu_497_p1),
    .q0(descramble_buf_1_M_real_V_q0),
    .address1(descramble_buf_1_M_real_V_address1),
    .ce1(descramble_buf_1_M_real_V_ce1),
    .q1(descramble_buf_1_M_real_V_q1)
);

hls_xfft2real_xfft2real_complex_ap_fixed_32_1_5_3_0_complex_ap_fixed_32_1_5_3_0_11_true_s_dg8j #(
    .DataWidth( 32 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
descramble_buf_0_M_imag_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(descramble_buf_0_M_imag_V_address0),
    .ce0(descramble_buf_0_M_imag_V_ce0),
    .we0(descramble_buf_0_M_imag_V_we0),
    .d0(descramble_buf_0_M_imag_V_d0),
    .q0(descramble_buf_0_M_imag_V_q0),
    .address1(descramble_buf_0_M_imag_V_address1),
    .ce1(descramble_buf_0_M_imag_V_ce1),
    .q1(descramble_buf_0_M_imag_V_q1)
);

hls_xfft2real_xfft2real_complex_ap_fixed_32_1_5_3_0_complex_ap_fixed_32_1_5_3_0_11_true_s_dg8j #(
    .DataWidth( 32 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
descramble_buf_1_M_imag_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(descramble_buf_1_M_imag_V_address0),
    .ce0(descramble_buf_1_M_imag_V_ce0),
    .we0(descramble_buf_1_M_imag_V_we0),
    .d0(descramble_buf_1_M_imag_V_d0),
    .q0(descramble_buf_1_M_imag_V_q0),
    .address1(descramble_buf_1_M_imag_V_address1),
    .ce1(descramble_buf_1_M_imag_V_ce1),
    .q1(descramble_buf_1_M_imag_V_q1)
);

hls_xfft2real_xfft2real_complex_ap_fixed_32_1_5_3_0_complex_ap_fixed_32_1_5_3_0_11_true_s_dg8j #(
    .DataWidth( 32 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
filter_buf_0_M_real_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(filter_buf_0_M_real_V_address0),
    .ce0(filter_buf_0_M_real_V_ce0),
    .we0(filter_buf_0_M_real_V_we0),
    .d0(p_r_V_3_reg_1866),
    .q0(filter_buf_0_M_real_V_q0),
    .address1(filter_buf_0_M_real_V_address1),
    .ce1(filter_buf_0_M_real_V_ce1),
    .q1(filter_buf_0_M_real_V_q1)
);

hls_xfft2real_xfft2real_complex_ap_fixed_32_1_5_3_0_complex_ap_fixed_32_1_5_3_0_11_true_s_dg8j #(
    .DataWidth( 32 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
filter_buf_1_M_real_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(filter_buf_1_M_real_V_address0),
    .ce0(filter_buf_1_M_real_V_ce0),
    .we0(filter_buf_1_M_real_V_we0),
    .d0(p_r_V_3_reg_1866),
    .q0(filter_buf_1_M_real_V_q0),
    .address1(filter_buf_1_M_real_V_address1),
    .ce1(filter_buf_1_M_real_V_ce1),
    .q1(filter_buf_1_M_real_V_q1)
);

hls_xfft2real_xfft2real_complex_ap_fixed_32_1_5_3_0_complex_ap_fixed_32_1_5_3_0_11_true_s_dg8j #(
    .DataWidth( 32 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
filter_buf_0_M_imag_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(filter_buf_0_M_imag_V_address0),
    .ce0(filter_buf_0_M_imag_V_ce0),
    .we0(filter_buf_0_M_imag_V_we0),
    .d0(p_r_M_imag_V_reg_1872),
    .q0(filter_buf_0_M_imag_V_q0),
    .address1(filter_buf_0_M_imag_V_address1),
    .ce1(filter_buf_0_M_imag_V_ce1),
    .q1(filter_buf_0_M_imag_V_q1)
);

hls_xfft2real_xfft2real_complex_ap_fixed_32_1_5_3_0_complex_ap_fixed_32_1_5_3_0_11_true_s_dg8j #(
    .DataWidth( 32 ),
    .AddressRange( 512 ),
    .AddressWidth( 9 ))
filter_buf_1_M_imag_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(filter_buf_1_M_imag_V_address0),
    .ce0(filter_buf_1_M_imag_V_ce0),
    .we0(filter_buf_1_M_imag_V_we0),
    .d0(p_r_M_imag_V_reg_1872),
    .q0(filter_buf_1_M_imag_V_q0),
    .address1(filter_buf_1_M_imag_V_address1),
    .ce1(filter_buf_1_M_imag_V_ce1),
    .q1(filter_buf_1_M_imag_V_q1)
);

hls_xfft2real_mul_32s_32s_63_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 63 ))
mul_32s_32s_63_3_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_822_p0),
    .din1(grp_fu_822_p1),
    .ce(1'b1),
    .dout(grp_fu_822_p2)
);

hls_xfft2real_mul_32s_32s_63_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 63 ))
mul_32s_32s_63_3_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_835_p0),
    .din1(grp_fu_835_p1),
    .ce(1'b1),
    .dout(grp_fu_835_p2)
);

hls_xfft2real_mul_32s_32s_63_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 63 ))
mul_32s_32s_63_3_1_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_841_p0),
    .din1(grp_fu_841_p1),
    .ce(1'b1),
    .dout(grp_fu_841_p2)
);

hls_xfft2real_mul_32s_32s_63_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 63 ))
mul_32s_32s_63_3_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_847_p0),
    .din1(grp_fu_847_p1),
    .ce(1'b1),
    .dout(grp_fu_847_p2)
);

hls_xfft2real_mul_32s_31ns_63_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 63 ))
mul_32s_31ns_63_3_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(cdata_M_real_V_3_reg_1845),
    .din1(grp_fu_1017_p1),
    .ce(1'b1),
    .dout(grp_fu_1017_p2)
);

hls_xfft2real_mul_32s_31ns_63_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 63 ))
mul_32s_31ns_63_3_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(cdata_M_imag_V_3_reg_1840),
    .din1(grp_fu_1026_p1),
    .ce(1'b1),
    .dout(grp_fu_1026_p2)
);

hls_xfft2real_mul_32s_32s_63_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 63 ))
mul_32s_32s_63_3_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1322_p0),
    .din1(grp_fu_1322_p1),
    .ce(grp_fu_1322_ce),
    .dout(grp_fu_1322_p2)
);

hls_xfft2real_mul_32s_31ns_63_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 63 ))
mul_32s_31ns_63_3_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1335_p0),
    .din1(grp_fu_1335_p1),
    .ce(grp_fu_1335_ce),
    .dout(grp_fu_1335_p2)
);

hls_xfft2real_mul_32s_32s_63_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 63 ))
mul_32s_32s_63_3_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1341_p0),
    .din1(grp_fu_1341_p1),
    .ce(grp_fu_1341_ce),
    .dout(grp_fu_1341_p2)
);

hls_xfft2real_mul_32s_31ns_63_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 31 ),
    .dout_WIDTH( 63 ))
mul_32s_31ns_63_3_1_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1347_p0),
    .din1(grp_fu_1347_p1),
    .ce(grp_fu_1347_ce),
    .dout(grp_fu_1347_p2)
);

hls_xfft2real_regslice_both #(
    .DataWidth( 64 ))
regslice_both_din_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(din_V_TDATA),
    .vld_in(din_V_TVALID),
    .ack_in(regslice_both_din_V_U_ack_in),
    .data_out(din_V_TDATA_int_regslice),
    .vld_out(din_V_TVALID_int_regslice),
    .ack_out(din_V_TREADY_int_regslice),
    .apdone_blk(regslice_both_din_V_U_apdone_blk)
);

hls_xfft2real_regslice_both #(
    .DataWidth( 64 ))
regslice_both_dout_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(dout_V_TDATA_int_regslice),
    .vld_in(dout_V_TVALID_int_regslice),
    .ack_in(dout_V_TREADY_int_regslice),
    .data_out(dout_V_TDATA),
    .vld_out(regslice_both_dout_V_U_vld_out),
    .ack_out(dout_V_TREADY),
    .apdone_blk(regslice_both_dout_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state24) & (regslice_both_dout_V_U_apdone_blk == 1'b0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_condition_pp1_exit_iter0_state4) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp1_exit_iter0_state4)) begin
                ap_enable_reg_pp1_iter1 <= (1'b1 ^ ap_condition_pp1_exit_iter0_state4);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter10 <= ap_enable_reg_pp1_iter9;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_enable_reg_pp1_iter10 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter2 <= ap_enable_reg_pp1_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter3 <= ap_enable_reg_pp1_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter4 <= ap_enable_reg_pp1_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter5 <= ap_enable_reg_pp1_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter6 <= ap_enable_reg_pp1_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter7 <= ap_enable_reg_pp1_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter8 <= ap_enable_reg_pp1_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter9 <= ap_enable_reg_pp1_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp2_stage0_subdone) & (1'b1 == ap_condition_pp2_exit_iter0_state16) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
            ap_enable_reg_pp2_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state15)) begin
            ap_enable_reg_pp2_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp2_exit_iter0_state16)) begin
                ap_enable_reg_pp2_iter1 <= (1'b1 ^ ap_condition_pp2_exit_iter0_state16);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp2_iter1 <= ap_enable_reg_pp2_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter2 <= ap_enable_reg_pp2_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter3 <= ap_enable_reg_pp2_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter4 <= ap_enable_reg_pp2_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter5 <= ap_enable_reg_pp2_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter6 <= ap_enable_reg_pp2_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp2_stage0_subdone)) begin
            ap_enable_reg_pp2_iter7 <= ap_enable_reg_pp2_iter6;
        end else if ((1'b1 == ap_CS_fsm_state15)) begin
            ap_enable_reg_pp2_iter7 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_1_reg_467 <= 11'd0;
    end else if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (icmp_ln95_reg_1619 == 1'd0))) begin
        i_1_reg_467 <= add_ln95_reg_1614;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state15)) begin
        i_2_reg_479 <= 11'd0;
    end else if (((icmp_ln117_reg_1883 == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        i_2_reg_479 <= add_ln117_reg_1878;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln86_fu_541_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (din_V_TVALID_int_regslice == 1'b1))) begin
        i_3171_reg_456 <= i_fu_491_p2;
    end else if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_3171_reg_456 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        add_ln117_reg_1878 <= add_ln117_fu_1052_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        add_ln95_reg_1614 <= add_ln95_fu_547_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp1_stage0_11001)) begin
        cdata_M_imag_V_3_reg_1840 <= cdata_M_imag_V_3_fu_989_p3;
        cdata_M_real_V_3_reg_1845 <= cdata_M_real_V_3_fu_996_p3;
        filter_buf_0_M_imag_V_addr_2_reg_1679_pp1_iter2_reg <= filter_buf_0_M_imag_V_addr_2_reg_1679_pp1_iter1_reg;
        filter_buf_0_M_imag_V_addr_2_reg_1679_pp1_iter3_reg <= filter_buf_0_M_imag_V_addr_2_reg_1679_pp1_iter2_reg;
        filter_buf_0_M_imag_V_addr_2_reg_1679_pp1_iter4_reg <= filter_buf_0_M_imag_V_addr_2_reg_1679_pp1_iter3_reg;
        filter_buf_0_M_imag_V_addr_2_reg_1679_pp1_iter5_reg <= filter_buf_0_M_imag_V_addr_2_reg_1679_pp1_iter4_reg;
        filter_buf_0_M_imag_V_addr_2_reg_1679_pp1_iter6_reg <= filter_buf_0_M_imag_V_addr_2_reg_1679_pp1_iter5_reg;
        filter_buf_0_M_imag_V_addr_2_reg_1679_pp1_iter7_reg <= filter_buf_0_M_imag_V_addr_2_reg_1679_pp1_iter6_reg;
        filter_buf_0_M_imag_V_addr_2_reg_1679_pp1_iter8_reg <= filter_buf_0_M_imag_V_addr_2_reg_1679_pp1_iter7_reg;
        filter_buf_0_M_imag_V_addr_2_reg_1679_pp1_iter9_reg <= filter_buf_0_M_imag_V_addr_2_reg_1679_pp1_iter8_reg;
        filter_buf_0_M_real_V_addr_2_reg_1669_pp1_iter2_reg <= filter_buf_0_M_real_V_addr_2_reg_1669_pp1_iter1_reg;
        filter_buf_0_M_real_V_addr_2_reg_1669_pp1_iter3_reg <= filter_buf_0_M_real_V_addr_2_reg_1669_pp1_iter2_reg;
        filter_buf_0_M_real_V_addr_2_reg_1669_pp1_iter4_reg <= filter_buf_0_M_real_V_addr_2_reg_1669_pp1_iter3_reg;
        filter_buf_0_M_real_V_addr_2_reg_1669_pp1_iter5_reg <= filter_buf_0_M_real_V_addr_2_reg_1669_pp1_iter4_reg;
        filter_buf_0_M_real_V_addr_2_reg_1669_pp1_iter6_reg <= filter_buf_0_M_real_V_addr_2_reg_1669_pp1_iter5_reg;
        filter_buf_0_M_real_V_addr_2_reg_1669_pp1_iter7_reg <= filter_buf_0_M_real_V_addr_2_reg_1669_pp1_iter6_reg;
        filter_buf_0_M_real_V_addr_2_reg_1669_pp1_iter8_reg <= filter_buf_0_M_real_V_addr_2_reg_1669_pp1_iter7_reg;
        filter_buf_0_M_real_V_addr_2_reg_1669_pp1_iter9_reg <= filter_buf_0_M_real_V_addr_2_reg_1669_pp1_iter8_reg;
        filter_buf_1_M_imag_V_addr_2_reg_1684_pp1_iter2_reg <= filter_buf_1_M_imag_V_addr_2_reg_1684_pp1_iter1_reg;
        filter_buf_1_M_imag_V_addr_2_reg_1684_pp1_iter3_reg <= filter_buf_1_M_imag_V_addr_2_reg_1684_pp1_iter2_reg;
        filter_buf_1_M_imag_V_addr_2_reg_1684_pp1_iter4_reg <= filter_buf_1_M_imag_V_addr_2_reg_1684_pp1_iter3_reg;
        filter_buf_1_M_imag_V_addr_2_reg_1684_pp1_iter5_reg <= filter_buf_1_M_imag_V_addr_2_reg_1684_pp1_iter4_reg;
        filter_buf_1_M_imag_V_addr_2_reg_1684_pp1_iter6_reg <= filter_buf_1_M_imag_V_addr_2_reg_1684_pp1_iter5_reg;
        filter_buf_1_M_imag_V_addr_2_reg_1684_pp1_iter7_reg <= filter_buf_1_M_imag_V_addr_2_reg_1684_pp1_iter6_reg;
        filter_buf_1_M_imag_V_addr_2_reg_1684_pp1_iter8_reg <= filter_buf_1_M_imag_V_addr_2_reg_1684_pp1_iter7_reg;
        filter_buf_1_M_imag_V_addr_2_reg_1684_pp1_iter9_reg <= filter_buf_1_M_imag_V_addr_2_reg_1684_pp1_iter8_reg;
        filter_buf_1_M_real_V_addr_2_reg_1674_pp1_iter2_reg <= filter_buf_1_M_real_V_addr_2_reg_1674_pp1_iter1_reg;
        filter_buf_1_M_real_V_addr_2_reg_1674_pp1_iter3_reg <= filter_buf_1_M_real_V_addr_2_reg_1674_pp1_iter2_reg;
        filter_buf_1_M_real_V_addr_2_reg_1674_pp1_iter4_reg <= filter_buf_1_M_real_V_addr_2_reg_1674_pp1_iter3_reg;
        filter_buf_1_M_real_V_addr_2_reg_1674_pp1_iter5_reg <= filter_buf_1_M_real_V_addr_2_reg_1674_pp1_iter4_reg;
        filter_buf_1_M_real_V_addr_2_reg_1674_pp1_iter6_reg <= filter_buf_1_M_real_V_addr_2_reg_1674_pp1_iter5_reg;
        filter_buf_1_M_real_V_addr_2_reg_1674_pp1_iter7_reg <= filter_buf_1_M_real_V_addr_2_reg_1674_pp1_iter6_reg;
        filter_buf_1_M_real_V_addr_2_reg_1674_pp1_iter8_reg <= filter_buf_1_M_real_V_addr_2_reg_1674_pp1_iter7_reg;
        filter_buf_1_M_real_V_addr_2_reg_1674_pp1_iter9_reg <= filter_buf_1_M_real_V_addr_2_reg_1674_pp1_iter8_reg;
        filter_rom_load_reg_1781 <= filter_rom_q0;
        filter_rom_load_reg_1781_pp1_iter3_reg <= filter_rom_load_reg_1781;
        filter_rom_load_reg_1781_pp1_iter4_reg <= filter_rom_load_reg_1781_pp1_iter3_reg;
        filter_rom_load_reg_1781_pp1_iter5_reg <= filter_rom_load_reg_1781_pp1_iter4_reg;
        filter_rom_load_reg_1781_pp1_iter6_reg <= filter_rom_load_reg_1781_pp1_iter5_reg;
        g_M_imag_V_reg_1766 <= g_M_imag_V_fu_795_p3;
        g_M_real_V_reg_1761 <= g_M_real_V_fu_766_p3;
        icmp_ln100_reg_1706_pp1_iter2_reg <= icmp_ln100_reg_1706;
        icmp_ln100_reg_1706_pp1_iter3_reg <= icmp_ln100_reg_1706_pp1_iter2_reg;
        icmp_ln100_reg_1706_pp1_iter4_reg <= icmp_ln100_reg_1706_pp1_iter3_reg;
        icmp_ln100_reg_1706_pp1_iter5_reg <= icmp_ln100_reg_1706_pp1_iter4_reg;
        icmp_ln97_reg_1689_pp1_iter2_reg <= icmp_ln97_reg_1689;
        icmp_ln97_reg_1689_pp1_iter3_reg <= icmp_ln97_reg_1689_pp1_iter2_reg;
        icmp_ln97_reg_1689_pp1_iter4_reg <= icmp_ln97_reg_1689_pp1_iter3_reg;
        icmp_ln97_reg_1689_pp1_iter5_reg <= icmp_ln97_reg_1689_pp1_iter4_reg;
        icmp_ln97_reg_1689_pp1_iter6_reg <= icmp_ln97_reg_1689_pp1_iter5_reg;
        icmp_ln97_reg_1689_pp1_iter7_reg <= icmp_ln97_reg_1689_pp1_iter6_reg;
        icmp_ln97_reg_1689_pp1_iter8_reg <= icmp_ln97_reg_1689_pp1_iter7_reg;
        icmp_ln97_reg_1689_pp1_iter9_reg <= icmp_ln97_reg_1689_pp1_iter8_reg;
        p_r_M_imag_V_reg_1872 <= {{grp_fu_1026_p2[62:31]}};
        p_r_V_3_reg_1866 <= {{grp_fu_1017_p2[62:31]}};
        ret_V_14_reg_1717_pp1_iter2_reg <= ret_V_14_reg_1717;
        ret_V_14_reg_1717_pp1_iter3_reg <= ret_V_14_reg_1717_pp1_iter2_reg;
        ret_V_14_reg_1717_pp1_iter4_reg <= ret_V_14_reg_1717_pp1_iter3_reg;
        ret_V_14_reg_1717_pp1_iter5_reg <= ret_V_14_reg_1717_pp1_iter4_reg;
        ret_V_15_reg_1754_pp1_iter3_reg <= ret_V_15_reg_1754;
        ret_V_15_reg_1754_pp1_iter4_reg <= ret_V_15_reg_1754_pp1_iter3_reg;
        ret_V_15_reg_1754_pp1_iter5_reg <= ret_V_15_reg_1754_pp1_iter4_reg;
        twid_rom_M_imag_V_load_reg_1776 <= twid_rom_M_imag_V_q0;
        twid_rom_M_real_V_load_reg_1771 <= twid_rom_M_real_V_q0;
        y1_M_imag_reg_1699_pp1_iter2_reg <= y1_M_imag_reg_1699;
        y1_M_imag_reg_1699_pp1_iter3_reg <= y1_M_imag_reg_1699_pp1_iter2_reg;
        y1_M_imag_reg_1699_pp1_iter4_reg <= y1_M_imag_reg_1699_pp1_iter3_reg;
        y1_M_imag_reg_1699_pp1_iter5_reg <= y1_M_imag_reg_1699_pp1_iter4_reg;
        y1_M_real_reg_1693_pp1_iter2_reg <= y1_M_real_reg_1693;
        y1_M_real_reg_1693_pp1_iter3_reg <= y1_M_real_reg_1693_pp1_iter2_reg;
        y1_M_real_reg_1693_pp1_iter4_reg <= y1_M_real_reg_1693_pp1_iter3_reg;
        y1_M_real_reg_1693_pp1_iter5_reg <= y1_M_real_reg_1693_pp1_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0) & (icmp_ln95_fu_553_p2 == 1'd0))) begin
        filter_buf_0_M_imag_V_addr_2_reg_1679 <= zext_ln97_fu_567_p1;
        filter_buf_0_M_real_V_addr_2_reg_1669 <= zext_ln97_fu_567_p1;
        filter_buf_1_M_imag_V_addr_2_reg_1684 <= zext_ln97_fu_567_p1;
        filter_buf_1_M_real_V_addr_2_reg_1674 <= zext_ln97_fu_567_p1;
        tmp_4_reg_1653 <= sub_ln703_fu_579_p2[32'd9];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        filter_buf_0_M_imag_V_addr_2_reg_1679_pp1_iter1_reg <= filter_buf_0_M_imag_V_addr_2_reg_1679;
        filter_buf_0_M_real_V_addr_2_reg_1669_pp1_iter1_reg <= filter_buf_0_M_real_V_addr_2_reg_1669;
        filter_buf_1_M_imag_V_addr_2_reg_1684_pp1_iter1_reg <= filter_buf_1_M_imag_V_addr_2_reg_1684;
        filter_buf_1_M_real_V_addr_2_reg_1674_pp1_iter1_reg <= filter_buf_1_M_real_V_addr_2_reg_1674;
        icmp_ln100_reg_1706 <= icmp_ln100_fu_644_p2;
        icmp_ln95_reg_1619 <= icmp_ln95_fu_553_p2;
        icmp_ln97_reg_1689 <= icmp_ln97_fu_622_p2;
        ret_V_14_reg_1717 <= ret_V_14_fu_678_p2;
        ret_V_16_reg_1724 <= ret_V_16_fu_684_p2;
        rhs_6_reg_1712 <= rhs_6_fu_661_p2;
        tmp_8_reg_1729 <= ret_V_16_fu_684_p2[32'd32];
        trunc_ln1148_11_reg_1734 <= {{ret_V_16_fu_684_p2[32:1]}};
        y1_M_imag_reg_1699 <= y1_M_imag_fu_636_p3;
        y1_M_real_reg_1693 <= y1_M_real_fu_628_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (icmp_ln121_reg_1938 == 1'd0) & (icmp_ln117_reg_1883_pp2_iter1_reg == 1'd0))) begin
        g_M_imag_V_1_reg_2004 <= g_M_imag_V_1_fu_1295_p3;
        g_M_real_V_1_reg_1999 <= g_M_real_V_1_fu_1266_p3;
        ret_V_20_reg_1992 <= ret_V_20_fu_1214_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        icmp_ln117_reg_1883 <= icmp_ln117_fu_1058_p2;
        icmp_ln117_reg_1883_pp2_iter1_reg <= icmp_ln117_reg_1883;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp2_stage0_11001)) begin
        icmp_ln117_reg_1883_pp2_iter2_reg <= icmp_ln117_reg_1883_pp2_iter1_reg;
        icmp_ln117_reg_1883_pp2_iter3_reg <= icmp_ln117_reg_1883_pp2_iter2_reg;
        icmp_ln117_reg_1883_pp2_iter4_reg <= icmp_ln117_reg_1883_pp2_iter3_reg;
        icmp_ln117_reg_1883_pp2_iter5_reg <= icmp_ln117_reg_1883_pp2_iter4_reg;
        icmp_ln117_reg_1883_pp2_iter6_reg <= icmp_ln117_reg_1883_pp2_iter5_reg;
        icmp_ln121_reg_1938_pp2_iter2_reg <= icmp_ln121_reg_1938;
        icmp_ln121_reg_1938_pp2_iter3_reg <= icmp_ln121_reg_1938_pp2_iter2_reg;
        icmp_ln121_reg_1938_pp2_iter4_reg <= icmp_ln121_reg_1938_pp2_iter3_reg;
        icmp_ln121_reg_1938_pp2_iter5_reg <= icmp_ln121_reg_1938_pp2_iter4_reg;
        ret_V_19_reg_1954_pp2_iter2_reg <= ret_V_19_reg_1954;
        ret_V_19_reg_1954_pp2_iter3_reg <= ret_V_19_reg_1954_pp2_iter2_reg;
        ret_V_19_reg_1954_pp2_iter4_reg <= ret_V_19_reg_1954_pp2_iter3_reg;
        ret_V_19_reg_1954_pp2_iter5_reg <= ret_V_19_reg_1954_pp2_iter4_reg;
        ret_V_20_reg_1992_pp2_iter3_reg <= ret_V_20_reg_1992;
        ret_V_20_reg_1992_pp2_iter4_reg <= ret_V_20_reg_1992_pp2_iter3_reg;
        ret_V_20_reg_1992_pp2_iter5_reg <= ret_V_20_reg_1992_pp2_iter4_reg;
        sext_ln703_1_reg_1943_pp2_iter2_reg <= sext_ln703_1_reg_1943;
        sext_ln703_1_reg_1943_pp2_iter3_reg <= sext_ln703_1_reg_1943_pp2_iter2_reg;
        sext_ln703_1_reg_1943_pp2_iter4_reg <= sext_ln703_1_reg_1943_pp2_iter3_reg;
        sext_ln703_2_reg_1986_pp2_iter3_reg <= sext_ln703_2_reg_1986;
        sext_ln703_2_reg_1986_pp2_iter4_reg <= sext_ln703_2_reg_1986_pp2_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln117_reg_1883 == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        icmp_ln121_reg_1938 <= icmp_ln121_fu_1144_p2;
        ret_V_19_reg_1954 <= ret_V_19_fu_1178_p2;
        ret_V_21_reg_1961 <= ret_V_21_fu_1184_p2;
        rhs_5_reg_1949 <= rhs_5_fu_1161_p2;
        rhs_7_reg_1933 <= rhs_7_fu_1136_p3;
        sext_ln703_1_reg_1943 <= sext_ln703_1_fu_1150_p1;
        tmp_16_reg_1966 <= ret_V_21_fu_1184_p2[32'd32];
        trunc_ln1148_19_reg_1971 <= {{ret_V_21_fu_1184_p2[32:1]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (icmp_ln121_reg_1938_pp2_iter4_reg == 1'd0) & (icmp_ln117_reg_1883_pp2_iter4_reg == 1'd0))) begin
        r_V_12_reg_2067 <= grp_fu_1322_p2;
        r_V_13_reg_2072 <= grp_fu_1335_p2;
        r_V_14_reg_2077 <= grp_fu_1341_p2;
        r_V_15_reg_2082 <= grp_fu_1347_p2;
        trunc_ln1148_12_reg_2057 <= {{sub_ln1148_12_fu_1361_p2[32:1]}};
        trunc_ln1148_14_reg_2062 <= {{sub_ln1148_14_fu_1376_p2[32:1]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln100_reg_1706_pp1_iter4_reg == 1'd0))) begin
        r_V_1_reg_1820 <= grp_fu_822_p2;
        r_V_3_reg_1825 <= grp_fu_835_p2;
        r_V_4_reg_1830 <= grp_fu_841_p2;
        r_V_5_reg_1835 <= grp_fu_847_p2;
        trunc_ln1148_7_reg_1810 <= {{sub_ln1148_4_fu_853_p2[32:1]}};
        trunc_ln1148_s_reg_1815 <= {{sub_ln1148_6_fu_868_p2[32:1]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (icmp_ln100_reg_1706 == 1'd0))) begin
        ret_V_15_reg_1754 <= ret_V_15_fu_714_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (icmp_ln121_reg_1938_pp2_iter4_reg == 1'd1) & (icmp_ln117_reg_1883_pp2_iter4_reg == 1'd0))) begin
        ret_V_17_reg_2043 <= ret_V_17_fu_1353_p2;
        ret_V_18_reg_2050 <= ret_V_18_fu_1357_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (icmp_ln117_reg_1883_pp2_iter1_reg == 1'd0))) begin
        sext_ln703_2_reg_1986 <= sext_ln703_2_fu_1208_p1;
        twid_rom_conj_M_imag_V_load_reg_2014 <= twid_rom_conj_M_imag_V_q0;
        twid_rom_conj_M_real_V_load_reg_2009 <= twid_rom_conj_M_real_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (icmp_ln117_fu_1058_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        tmp_12_reg_1917 <= sub_ln703_2_fu_1080_p2[32'd9];
    end
end

always @ (*) begin
    if ((icmp_ln95_fu_553_p2 == 1'd1)) begin
        ap_condition_pp1_exit_iter0_state4 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter0_state4 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln117_fu_1058_p2 == 1'd1)) begin
        ap_condition_pp2_exit_iter0_state16 = 1'b1;
    end else begin
        ap_condition_pp2_exit_iter0_state16 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state24) & (regslice_both_dout_V_U_apdone_blk == 1'b0))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter10 == 1'b0) & (ap_enable_reg_pp1_iter9 == 1'b0) & (ap_enable_reg_pp1_iter8 == 1'b0) & (ap_enable_reg_pp1_iter7 == 1'b0) & (ap_enable_reg_pp1_iter6 == 1'b0) & (ap_enable_reg_pp1_iter5 == 1'b0) & (ap_enable_reg_pp1_iter4 == 1'b0) & (ap_enable_reg_pp1_iter3 == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter7 == 1'b0) & (ap_enable_reg_pp2_iter6 == 1'b0) & (ap_enable_reg_pp2_iter5 == 1'b0) & (ap_enable_reg_pp2_iter4 == 1'b0) & (ap_enable_reg_pp2_iter3 == 1'b0) & (ap_enable_reg_pp2_iter2 == 1'b0) & (ap_enable_reg_pp2_iter1 == 1'b0) & (ap_enable_reg_pp2_iter0 == 1'b0))) begin
        ap_idle_pp2 = 1'b1;
    end else begin
        ap_idle_pp2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (icmp_ln95_reg_1619 == 1'd0))) begin
        ap_phi_mux_i_1_phi_fu_471_p4 = add_ln95_reg_1614;
    end else begin
        ap_phi_mux_i_1_phi_fu_471_p4 = i_1_reg_467;
    end
end

always @ (*) begin
    if (((icmp_ln117_reg_1883 == 1'd0) & (1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        ap_phi_mux_i_2_phi_fu_483_p4 = add_ln117_reg_1878;
    end else begin
        ap_phi_mux_i_2_phi_fu_483_p4 = i_2_reg_479;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state24) & (regslice_both_dout_V_U_apdone_blk == 1'b0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        descramble_buf_0_M_imag_V_address0 = zext_ln703_fu_589_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        descramble_buf_0_M_imag_V_address0 = zext_ln92_fu_525_p1;
    end else begin
        descramble_buf_0_M_imag_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & (din_V_TVALID_int_regslice == 1'b1)) | ((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1)))) begin
        descramble_buf_0_M_imag_V_ce0 = 1'b1;
    end else begin
        descramble_buf_0_M_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        descramble_buf_0_M_imag_V_ce1 = 1'b1;
    end else begin
        descramble_buf_0_M_imag_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_2_fu_533_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (din_V_TVALID_int_regslice == 1'b1))) begin
        descramble_buf_0_M_imag_V_we0 = 1'b1;
    end else begin
        descramble_buf_0_M_imag_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        descramble_buf_0_M_real_V_address0 = zext_ln703_fu_589_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        descramble_buf_0_M_real_V_address0 = zext_ln92_fu_525_p1;
    end else begin
        descramble_buf_0_M_real_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & (din_V_TVALID_int_regslice == 1'b1)) | ((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1)))) begin
        descramble_buf_0_M_real_V_ce0 = 1'b1;
    end else begin
        descramble_buf_0_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        descramble_buf_0_M_real_V_ce1 = 1'b1;
    end else begin
        descramble_buf_0_M_real_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_2_fu_533_p3 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (din_V_TVALID_int_regslice == 1'b1))) begin
        descramble_buf_0_M_real_V_we0 = 1'b1;
    end else begin
        descramble_buf_0_M_real_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        descramble_buf_1_M_imag_V_address0 = zext_ln703_fu_589_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        descramble_buf_1_M_imag_V_address0 = zext_ln92_fu_525_p1;
    end else begin
        descramble_buf_1_M_imag_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & (din_V_TVALID_int_regslice == 1'b1)) | ((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1)))) begin
        descramble_buf_1_M_imag_V_ce0 = 1'b1;
    end else begin
        descramble_buf_1_M_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        descramble_buf_1_M_imag_V_ce1 = 1'b1;
    end else begin
        descramble_buf_1_M_imag_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_2_fu_533_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (din_V_TVALID_int_regslice == 1'b1))) begin
        descramble_buf_1_M_imag_V_we0 = 1'b1;
    end else begin
        descramble_buf_1_M_imag_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        descramble_buf_1_M_real_V_address0 = zext_ln703_fu_589_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        descramble_buf_1_M_real_V_address0 = zext_ln92_fu_525_p1;
    end else begin
        descramble_buf_1_M_real_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state2) & (din_V_TVALID_int_regslice == 1'b1)) | ((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1)))) begin
        descramble_buf_1_M_real_V_ce0 = 1'b1;
    end else begin
        descramble_buf_1_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        descramble_buf_1_M_real_V_ce1 = 1'b1;
    end else begin
        descramble_buf_1_M_real_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_2_fu_533_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (din_V_TVALID_int_regslice == 1'b1))) begin
        descramble_buf_1_M_real_V_we0 = 1'b1;
    end else begin
        descramble_buf_1_M_real_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        din_V_TDATA_blk_n = din_V_TVALID_int_regslice;
    end else begin
        din_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (din_V_TVALID_int_regslice == 1'b1))) begin
        din_V_TREADY_int_regslice = 1'b1;
    end else begin
        din_V_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln117_reg_1883_pp2_iter6_reg == 1'd0) & (ap_enable_reg_pp2_iter7 == 1'b1) & (1'b0 == ap_block_pp2_stage0)) | ((icmp_ln117_reg_1883_pp2_iter5_reg == 1'd0) & (1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter6 == 1'b1)))) begin
        dout_V_TDATA_blk_n = dout_V_TREADY_int_regslice;
    end else begin
        dout_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln117_reg_1883_pp2_iter5_reg == 1'd0) & (1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter6 == 1'b1))) begin
        dout_V_TVALID_int_regslice = 1'b1;
    end else begin
        dout_V_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        filter_buf_0_M_imag_V_address0 = zext_ln703_1_fu_1090_p1;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter10 == 1'b1))) begin
        filter_buf_0_M_imag_V_address0 = filter_buf_0_M_imag_V_addr_2_reg_1679_pp1_iter9_reg;
    end else begin
        filter_buf_0_M_imag_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)) | ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter10 == 1'b1)))) begin
        filter_buf_0_M_imag_V_ce0 = 1'b1;
    end else begin
        filter_buf_0_M_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        filter_buf_0_M_imag_V_ce1 = 1'b1;
    end else begin
        filter_buf_0_M_imag_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter10 == 1'b1) & (icmp_ln97_reg_1689_pp1_iter9_reg == 1'd1))) begin
        filter_buf_0_M_imag_V_we0 = 1'b1;
    end else begin
        filter_buf_0_M_imag_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        filter_buf_0_M_real_V_address0 = zext_ln703_1_fu_1090_p1;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter10 == 1'b1))) begin
        filter_buf_0_M_real_V_address0 = filter_buf_0_M_real_V_addr_2_reg_1669_pp1_iter9_reg;
    end else begin
        filter_buf_0_M_real_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)) | ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter10 == 1'b1)))) begin
        filter_buf_0_M_real_V_ce0 = 1'b1;
    end else begin
        filter_buf_0_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        filter_buf_0_M_real_V_ce1 = 1'b1;
    end else begin
        filter_buf_0_M_real_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter10 == 1'b1) & (icmp_ln97_reg_1689_pp1_iter9_reg == 1'd1))) begin
        filter_buf_0_M_real_V_we0 = 1'b1;
    end else begin
        filter_buf_0_M_real_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        filter_buf_1_M_imag_V_address0 = zext_ln703_1_fu_1090_p1;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter10 == 1'b1))) begin
        filter_buf_1_M_imag_V_address0 = filter_buf_1_M_imag_V_addr_2_reg_1684_pp1_iter9_reg;
    end else begin
        filter_buf_1_M_imag_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)) | ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter10 == 1'b1)))) begin
        filter_buf_1_M_imag_V_ce0 = 1'b1;
    end else begin
        filter_buf_1_M_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        filter_buf_1_M_imag_V_ce1 = 1'b1;
    end else begin
        filter_buf_1_M_imag_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter10 == 1'b1) & (icmp_ln97_reg_1689_pp1_iter9_reg == 1'd0))) begin
        filter_buf_1_M_imag_V_we0 = 1'b1;
    end else begin
        filter_buf_1_M_imag_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        filter_buf_1_M_real_V_address0 = zext_ln703_1_fu_1090_p1;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter10 == 1'b1))) begin
        filter_buf_1_M_real_V_address0 = filter_buf_1_M_real_V_addr_2_reg_1674_pp1_iter9_reg;
    end else begin
        filter_buf_1_M_real_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0)) | ((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter10 == 1'b1)))) begin
        filter_buf_1_M_real_V_ce0 = 1'b1;
    end else begin
        filter_buf_1_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        filter_buf_1_M_real_V_ce1 = 1'b1;
    end else begin
        filter_buf_1_M_real_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter10 == 1'b1) & (icmp_ln97_reg_1689_pp1_iter9_reg == 1'd0))) begin
        filter_buf_1_M_real_V_we0 = 1'b1;
    end else begin
        filter_buf_1_M_real_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        filter_rom_ce0 = 1'b1;
    end else begin
        filter_rom_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        grp_fu_1322_ce = 1'b1;
    end else begin
        grp_fu_1322_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        grp_fu_1335_ce = 1'b1;
    end else begin
        grp_fu_1335_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        grp_fu_1341_ce = 1'b1;
    end else begin
        grp_fu_1341_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        grp_fu_1347_ce = 1'b1;
    end else begin
        grp_fu_1347_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        twid_rom_M_imag_V_ce0 = 1'b1;
    end else begin
        twid_rom_M_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        twid_rom_M_real_V_ce0 = 1'b1;
    end else begin
        twid_rom_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        twid_rom_conj_M_imag_V_ce0 = 1'b1;
    end else begin
        twid_rom_conj_M_imag_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage0_11001) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        twid_rom_conj_M_real_V_ce0 = 1'b1;
    end else begin
        twid_rom_conj_M_real_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln86_fu_541_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2) & (din_V_TVALID_int_regslice == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else if (((icmp_ln86_fu_541_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (din_V_TVALID_int_regslice == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_pp1_stage0;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if ((~((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter1 == 1'b0) & (icmp_ln95_fu_553_p2 == 1'd1) & (ap_enable_reg_pp1_iter0 == 1'b1)) & ~((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter10 == 1'b1) & (ap_enable_reg_pp1_iter9 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if ((((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter10 == 1'b1) & (ap_enable_reg_pp1_iter9 == 1'b0)) | ((1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter1 == 1'b0) & (icmp_ln95_fu_553_p2 == 1'd1) & (ap_enable_reg_pp1_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_pp2_stage0;
        end
        ap_ST_fsm_pp2_stage0 : begin
            if ((~((1'b0 == ap_block_pp2_stage0_subdone) & (ap_enable_reg_pp2_iter1 == 1'b0) & (icmp_ln117_fu_1058_p2 == 1'd1) & (ap_enable_reg_pp2_iter0 == 1'b1)) & ~((ap_enable_reg_pp2_iter7 == 1'b1) & (1'b0 == ap_block_pp2_stage0_subdone) & (ap_enable_reg_pp2_iter6 == 1'b0)))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else if ((((ap_enable_reg_pp2_iter7 == 1'b1) & (1'b0 == ap_block_pp2_stage0_subdone) & (ap_enable_reg_pp2_iter6 == 1'b0)) | ((1'b0 == ap_block_pp2_stage0_subdone) & (ap_enable_reg_pp2_iter1 == 1'b0) & (icmp_ln117_fu_1058_p2 == 1'd1) & (ap_enable_reg_pp2_iter0 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end
        end
        ap_ST_fsm_state24 : begin
            if (((1'b1 == ap_CS_fsm_state24) & (regslice_both_dout_V_U_apdone_blk == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln117_fu_1052_p2 = (ap_phi_mux_i_2_phi_fu_483_p4 + 11'd1);

assign add_ln95_fu_547_p2 = (ap_phi_mux_i_1_phi_fu_471_p4 + 11'd1);

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp2_stage0 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp2_stage0_01001 = (((icmp_ln117_reg_1883_pp2_iter6_reg == 1'd0) & (ap_enable_reg_pp2_iter7 == 1'b1) & (dout_V_TREADY_int_regslice == 1'b0)) | ((icmp_ln117_reg_1883_pp2_iter5_reg == 1'd0) & (ap_enable_reg_pp2_iter6 == 1'b1) & (dout_V_TREADY_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_pp2_stage0_11001 = (((ap_enable_reg_pp2_iter7 == 1'b1) & ((1'b1 == ap_block_state23_io) | ((icmp_ln117_reg_1883_pp2_iter6_reg == 1'd0) & (dout_V_TREADY_int_regslice == 1'b0)))) | ((ap_enable_reg_pp2_iter6 == 1'b1) & ((1'b1 == ap_block_state22_io) | ((icmp_ln117_reg_1883_pp2_iter5_reg == 1'd0) & (dout_V_TREADY_int_regslice == 1'b0)))));
end

always @ (*) begin
    ap_block_pp2_stage0_subdone = (((ap_enable_reg_pp2_iter7 == 1'b1) & ((1'b1 == ap_block_state23_io) | ((icmp_ln117_reg_1883_pp2_iter6_reg == 1'd0) & (dout_V_TREADY_int_regslice == 1'b0)))) | ((ap_enable_reg_pp2_iter6 == 1'b1) & ((1'b1 == ap_block_state22_io) | ((icmp_ln117_reg_1883_pp2_iter5_reg == 1'd0) & (dout_V_TREADY_int_regslice == 1'b0)))));
end

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign ap_block_state10_pp1_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp1_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp1_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp1_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp1_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp2_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp2_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp2_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp2_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp2_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp2_stage0_iter5 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state22_io = ((icmp_ln117_reg_1883_pp2_iter5_reg == 1'd0) & (dout_V_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state22_pp2_stage0_iter6 = ((icmp_ln117_reg_1883_pp2_iter5_reg == 1'd0) & (dout_V_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state23_io = ((icmp_ln117_reg_1883_pp2_iter6_reg == 1'd0) & (dout_V_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state23_pp2_stage0_iter7 = ((icmp_ln117_reg_1883_pp2_iter6_reg == 1'd0) & (dout_V_TREADY_int_regslice == 1'b0));
end

assign ap_block_state4_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp1_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp1_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp1_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp1_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp1_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign ap_enable_pp2 = (ap_idle_pp2 ^ 1'b1);

assign cdata_M_imag_V_3_fu_989_p3 = ((icmp_ln100_reg_1706_pp1_iter5_reg[0:0] == 1'b1) ? cdata_M_imag_V_fu_887_p2 : p_r_M_imag_V_6_fu_983_p2);

assign cdata_M_imag_V_fu_887_p2 = ($signed(y1_M_real_reg_1693_pp1_iter5_reg) - $signed(y1_M_imag_reg_1699_pp1_iter5_reg));

assign cdata_M_real_V_3_fu_996_p3 = ((icmp_ln100_reg_1706_pp1_iter5_reg[0:0] == 1'b1) ? cdata_M_real_V_fu_883_p2 : p_r_M_real_V_fu_977_p2);

assign cdata_M_real_V_fu_883_p2 = ($signed(y1_M_imag_reg_1699_pp1_iter5_reg) + $signed(y1_M_real_reg_1693_pp1_iter5_reg));

assign descramble_buf_0_M_imag_V_address1 = zext_ln97_fu_567_p1;

assign descramble_buf_0_M_imag_V_d0 = {{din_V_TDATA_int_regslice[63:32]}};

assign descramble_buf_0_M_real_V_address1 = zext_ln97_fu_567_p1;

assign descramble_buf_1_M_imag_V_address1 = zext_ln97_fu_567_p1;

assign descramble_buf_1_M_imag_V_d0 = {{din_V_TDATA_int_regslice[63:32]}};

assign descramble_buf_1_M_real_V_address1 = zext_ln97_fu_567_p1;

assign din_V_TREADY = regslice_both_din_V_U_ack_in;

assign dout_V_TDATA_int_regslice = ((icmp_ln121_reg_1938_pp2_iter5_reg[0:0] == 1'b1) ? tmp_fu_1481_p3 : tmp_1_fu_1587_p3);

assign dout_V_TVALID = regslice_both_dout_V_U_vld_out;

assign f_M_imag_V_1_fu_1539_p3 = ((tmp_14_fu_1518_p3[0:0] == 1'b1) ? sub_ln1148_15_fu_1525_p2 : trunc_ln1148_15_fu_1530_p4);

assign f_M_imag_V_fu_941_p3 = ((tmp_6_fu_920_p3[0:0] == 1'b1) ? sub_ln1148_7_fu_927_p2 : trunc_ln1148_3_fu_932_p4);

assign f_M_real_V_1_fu_1510_p3 = ((tmp_13_fu_1489_p3[0:0] == 1'b1) ? sub_ln1148_13_fu_1496_p2 : trunc_ln1148_13_fu_1501_p4);

assign f_M_real_V_fu_912_p3 = ((tmp_5_fu_891_p3[0:0] == 1'b1) ? sub_ln1148_5_fu_898_p2 : trunc_ln1148_8_fu_903_p4);

assign filter_buf_0_M_imag_V_address1 = zext_ln119_fu_1072_p1;

assign filter_buf_0_M_real_V_address1 = zext_ln119_fu_1072_p1;

assign filter_buf_1_M_imag_V_address1 = zext_ln119_fu_1072_p1;

assign filter_buf_1_M_real_V_address1 = zext_ln119_fu_1072_p1;

assign filter_rom_address0 = zext_ln95_fu_605_p1;

assign g_M_imag_V_1_fu_1295_p3 = ((tmp_16_reg_1966[0:0] == 1'b1) ? sub_ln1148_19_fu_1289_p2 : trunc_ln1148_19_reg_1971);

assign g_M_imag_V_fu_795_p3 = ((tmp_8_reg_1729[0:0] == 1'b1) ? sub_ln1148_11_fu_789_p2 : trunc_ln1148_11_reg_1734);

assign g_M_real_V_1_fu_1266_p3 = ((tmp_15_fu_1226_p3[0:0] == 1'b1) ? trunc_ln1148_17_fu_1256_p4 : sub_ln1148_17_fu_1250_p2);

assign g_M_real_V_fu_766_p3 = ((tmp_7_fu_726_p3[0:0] == 1'b1) ? trunc_ln1148_9_fu_756_p4 : sub_ln1148_9_fu_750_p2);

assign grp_fu_1017_p1 = zext_ln1118_fu_1013_p1;

assign grp_fu_1026_p1 = zext_ln1118_fu_1013_p1;

assign grp_fu_1322_p0 = sext_ln1115_4_fu_1315_p1;

assign grp_fu_1322_p1 = sext_ln1118_2_fu_1319_p1;

assign grp_fu_1335_p0 = sext_ln1118_3_fu_1332_p1;

assign grp_fu_1335_p1 = zext_ln1115_fu_1328_p1;

assign grp_fu_1341_p0 = sext_ln1115_4_fu_1315_p1;

assign grp_fu_1341_p1 = sext_ln1118_3_fu_1332_p1;

assign grp_fu_1347_p0 = sext_ln1118_2_fu_1319_p1;

assign grp_fu_1347_p1 = zext_ln1115_fu_1328_p1;

assign grp_fu_822_p0 = sext_ln1115_fu_815_p1;

assign grp_fu_822_p1 = sext_ln1118_fu_819_p1;

assign grp_fu_835_p0 = sext_ln1115_1_fu_828_p1;

assign grp_fu_835_p1 = sext_ln1118_1_fu_832_p1;

assign grp_fu_841_p0 = sext_ln1115_fu_815_p1;

assign grp_fu_841_p1 = sext_ln1118_1_fu_832_p1;

assign grp_fu_847_p0 = sext_ln1115_1_fu_828_p1;

assign grp_fu_847_p1 = sext_ln1118_fu_819_p1;

assign i_fu_491_p2 = (i_3171_reg_456 + 10'd1);

assign icmp_ln100_fu_644_p2 = ((i_1_reg_467 == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln117_fu_1058_p2 = ((ap_phi_mux_i_2_phi_fu_483_p4 == 11'd1024) ? 1'b1 : 1'b0);

assign icmp_ln119_fu_1122_p2 = ((tmp_9_fu_1112_p4 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln121_fu_1144_p2 = ((i_2_reg_479 == 11'd0) ? 1'b1 : 1'b0);

assign icmp_ln86_fu_541_p2 = ((i_3171_reg_456 == 10'd1023) ? 1'b1 : 1'b0);

assign icmp_ln95_fu_553_p2 = ((ap_phi_mux_i_1_phi_fu_471_p4 == 11'd1024) ? 1'b1 : 1'b0);

assign icmp_ln97_fu_622_p2 = ((tmp_3_fu_612_p4 == 2'd0) ? 1'b1 : 1'b0);

assign lhs_V_fu_1128_p3 = ((icmp_ln119_fu_1122_p2[0:0] == 1'b1) ? filter_buf_0_M_real_V_q1 : filter_buf_1_M_real_V_q1);

assign p_r_M_imag_V_5_fu_1581_p2 = (trunc_ln708_3_fu_1565_p4 + f_M_imag_V_1_fu_1539_p3);

assign p_r_M_imag_V_6_fu_983_p2 = (trunc_ln5_fu_967_p4 + f_M_imag_V_fu_941_p3);

assign p_r_M_real_V_6_fu_1575_p2 = (p_r_V_2_fu_1551_p4 + f_M_real_V_1_fu_1510_p3);

assign p_r_M_real_V_fu_977_p2 = (p_r_V_fu_953_p4 + f_M_real_V_fu_912_p3);

assign p_r_V_2_fu_1551_p4 = {{ret_V_12_fu_1547_p2[62:31]}};

assign p_r_V_fu_953_p4 = {{ret_V_4_fu_949_p2[62:31]}};

assign r_V_10_fu_1308_p3 = {{twid_rom_conj_M_imag_V_load_reg_2014}, {8'd0}};

assign r_V_11_fu_1301_p3 = {{twid_rom_conj_M_real_V_load_reg_2009}, {8'd0}};

assign r_V_2_fu_808_p3 = {{twid_rom_M_imag_V_load_reg_1776}, {8'd0}};

assign r_V_fu_801_p3 = {{twid_rom_M_real_V_load_reg_1771}, {8'd0}};

assign ret_V_10_fu_1220_p2 = ($signed(sext_ln703_2_fu_1208_p1) - $signed(sext_ln703_7_fu_1211_p1));

assign ret_V_12_fu_1547_p2 = (r_V_12_reg_2067 - r_V_13_reg_2072);

assign ret_V_13_fu_1561_p2 = (r_V_15_reg_2082 + r_V_14_reg_2077);

assign ret_V_14_fu_678_p2 = ($signed(sext_ln703_3_fu_674_p1) + $signed(sext_ln703_fu_650_p1));

assign ret_V_15_fu_714_p2 = ($signed(sext_ln703_5_fu_711_p1) + $signed(sext_ln703_4_fu_708_p1));

assign ret_V_16_fu_684_p2 = ($signed(sext_ln703_3_fu_674_p1) - $signed(sext_ln703_fu_650_p1));

assign ret_V_17_fu_1353_p2 = ($signed(sext_ln703_2_reg_1986_pp2_iter4_reg) + $signed(sext_ln703_1_reg_1943_pp2_iter4_reg));

assign ret_V_18_fu_1357_p2 = ($signed(sext_ln703_1_reg_1943_pp2_iter4_reg) - $signed(sext_ln703_2_reg_1986_pp2_iter4_reg));

assign ret_V_19_fu_1178_p2 = ($signed(sext_ln703_6_fu_1174_p1) + $signed(sext_ln703_1_fu_1150_p1));

assign ret_V_20_fu_1214_p2 = ($signed(sext_ln703_7_fu_1211_p1) + $signed(sext_ln703_2_fu_1208_p1));

assign ret_V_21_fu_1184_p2 = ($signed(sext_ln703_1_fu_1150_p1) - $signed(sext_ln703_6_fu_1174_p1));

assign ret_V_4_fu_949_p2 = (r_V_1_reg_1820 - r_V_3_reg_1825);

assign ret_V_5_fu_963_p2 = (r_V_5_reg_1835 + r_V_4_reg_1830);

assign ret_V_fu_720_p2 = ($signed(sext_ln703_5_fu_711_p1) - $signed(sext_ln703_4_fu_708_p1));

assign rhs_4_fu_1167_p3 = ((tmp_12_reg_1917[0:0] == 1'b1) ? filter_buf_1_M_real_V_q0 : filter_buf_0_M_real_V_q0);

assign rhs_5_fu_1161_p2 = (32'd0 - select_ln703_2_fu_1154_p3);

assign rhs_6_fu_661_p2 = (32'd0 - select_ln703_fu_654_p3);

assign rhs_7_fu_1136_p3 = ((icmp_ln119_fu_1122_p2[0:0] == 1'b1) ? filter_buf_0_M_imag_V_q1 : filter_buf_1_M_imag_V_q1);

assign rhs_fu_667_p3 = ((tmp_4_reg_1653[0:0] == 1'b1) ? descramble_buf_1_M_real_V_q0 : descramble_buf_0_M_real_V_q0);

assign select_ln1148_1_fu_1473_p3 = ((tmp_11_fu_1436_p3[0:0] == 1'b1) ? sub_ln1148_3_fu_1458_p2 : trunc_ln1148_5_fu_1464_p4);

assign select_ln1148_fu_1428_p3 = ((tmp_10_fu_1391_p3[0:0] == 1'b1) ? sub_ln1148_1_fu_1413_p2 : trunc_ln1148_2_fu_1419_p4);

assign select_ln703_2_fu_1154_p3 = ((tmp_12_reg_1917[0:0] == 1'b1) ? filter_buf_1_M_imag_V_q0 : filter_buf_0_M_imag_V_q0);

assign select_ln703_fu_654_p3 = ((tmp_4_reg_1653[0:0] == 1'b1) ? descramble_buf_1_M_imag_V_q0 : descramble_buf_0_M_imag_V_q0);

assign sext_ln1115_1_fu_828_p1 = $signed(r_V_2_fu_808_p3);

assign sext_ln1115_4_fu_1315_p1 = $signed(r_V_11_fu_1301_p3);

assign sext_ln1115_fu_815_p1 = $signed(r_V_fu_801_p3);

assign sext_ln1118_1_fu_832_p1 = $signed(g_M_imag_V_reg_1766);

assign sext_ln1118_2_fu_1319_p1 = $signed(g_M_real_V_1_reg_1999);

assign sext_ln1118_3_fu_1332_p1 = $signed(g_M_imag_V_1_reg_2004);

assign sext_ln1118_fu_819_p1 = $signed(g_M_real_V_reg_1761);

assign sext_ln703_1_fu_1150_p1 = $signed(lhs_V_fu_1128_p3);

assign sext_ln703_2_fu_1208_p1 = $signed(rhs_7_reg_1933);

assign sext_ln703_3_fu_674_p1 = $signed(rhs_fu_667_p3);

assign sext_ln703_4_fu_708_p1 = y1_M_imag_reg_1699;

assign sext_ln703_5_fu_711_p1 = $signed(rhs_6_reg_1712);

assign sext_ln703_6_fu_1174_p1 = $signed(rhs_4_fu_1167_p3);

assign sext_ln703_7_fu_1211_p1 = $signed(rhs_5_reg_1949);

assign sext_ln703_fu_650_p1 = y1_M_real_fu_628_p3;

assign shl_ln_fu_1003_p3 = {{filter_rom_load_reg_1781_pp1_iter6_reg}, {8'd0}};

assign sub_ln1148_10_fu_774_p2 = (33'd0 - ret_V_16_reg_1724);

assign sub_ln1148_11_fu_789_p2 = (32'd0 - trunc_ln1148_10_fu_779_p4);

assign sub_ln1148_12_fu_1361_p2 = (33'd0 - ret_V_19_reg_1954_pp2_iter4_reg);

assign sub_ln1148_13_fu_1496_p2 = (32'd0 - trunc_ln1148_12_reg_2057);

assign sub_ln1148_14_fu_1376_p2 = (33'd0 - ret_V_20_reg_1992_pp2_iter4_reg);

assign sub_ln1148_15_fu_1525_p2 = (32'd0 - trunc_ln1148_14_reg_2062);

assign sub_ln1148_16_fu_1234_p2 = (33'd0 - ret_V_10_fu_1220_p2);

assign sub_ln1148_17_fu_1250_p2 = (32'd0 - trunc_ln1148_16_fu_1240_p4);

assign sub_ln1148_18_fu_1274_p2 = (33'd0 - ret_V_21_reg_1961);

assign sub_ln1148_19_fu_1289_p2 = (32'd0 - trunc_ln1148_18_fu_1279_p4);

assign sub_ln1148_1_fu_1413_p2 = (32'd0 - trunc_ln1148_1_fu_1403_p4);

assign sub_ln1148_2_fu_1443_p2 = (33'd0 - ret_V_18_reg_2050);

assign sub_ln1148_3_fu_1458_p2 = (32'd0 - trunc_ln1148_4_fu_1448_p4);

assign sub_ln1148_4_fu_853_p2 = (33'd0 - ret_V_14_reg_1717_pp1_iter4_reg);

assign sub_ln1148_5_fu_898_p2 = (32'd0 - trunc_ln1148_7_reg_1810);

assign sub_ln1148_6_fu_868_p2 = (33'd0 - ret_V_15_reg_1754_pp1_iter4_reg);

assign sub_ln1148_7_fu_927_p2 = (32'd0 - trunc_ln1148_s_reg_1815);

assign sub_ln1148_8_fu_734_p2 = (33'd0 - ret_V_fu_720_p2);

assign sub_ln1148_9_fu_750_p2 = (32'd0 - trunc_ln1148_6_fu_740_p4);

assign sub_ln1148_fu_1398_p2 = (33'd0 - ret_V_17_reg_2043);

assign sub_ln703_2_fu_1080_p2 = (10'd0 - trunc_ln117_fu_1064_p1);

assign sub_ln703_fu_579_p2 = (10'd0 - trunc_ln95_fu_559_p1);

assign tmp_10_fu_1391_p3 = ret_V_17_reg_2043[32'd32];

assign tmp_11_fu_1436_p3 = ret_V_18_reg_2050[32'd32];

assign tmp_13_fu_1489_p3 = ret_V_19_reg_1954_pp2_iter5_reg[32'd32];

assign tmp_14_fu_1518_p3 = ret_V_20_reg_1992_pp2_iter5_reg[32'd32];

assign tmp_15_fu_1226_p3 = ret_V_10_fu_1220_p2[32'd32];

assign tmp_1_fu_1587_p3 = {{p_r_M_imag_V_5_fu_1581_p2}, {p_r_M_real_V_6_fu_1575_p2}};

assign tmp_2_fu_533_p3 = i_3171_reg_456[32'd0];

assign tmp_3_fu_612_p4 = {{i_1_reg_467[10:9]}};

assign tmp_5_fu_891_p3 = ret_V_14_reg_1717_pp1_iter5_reg[32'd32];

assign tmp_6_fu_920_p3 = ret_V_15_reg_1754_pp1_iter5_reg[32'd32];

assign tmp_7_fu_726_p3 = ret_V_fu_720_p2[32'd32];

assign tmp_9_fu_1112_p4 = {{i_2_reg_479[10:9]}};

assign tmp_fu_1481_p3 = {{select_ln1148_1_fu_1473_p3}, {select_ln1148_fu_1428_p3}};

assign trunc_ln1148_10_fu_779_p4 = {{sub_ln1148_10_fu_774_p2[32:1]}};

assign trunc_ln1148_13_fu_1501_p4 = {{ret_V_19_reg_1954_pp2_iter5_reg[32:1]}};

assign trunc_ln1148_15_fu_1530_p4 = {{ret_V_20_reg_1992_pp2_iter5_reg[32:1]}};

assign trunc_ln1148_16_fu_1240_p4 = {{ret_V_10_fu_1220_p2[32:1]}};

assign trunc_ln1148_17_fu_1256_p4 = {{sub_ln1148_16_fu_1234_p2[32:1]}};

assign trunc_ln1148_18_fu_1279_p4 = {{sub_ln1148_18_fu_1274_p2[32:1]}};

assign trunc_ln1148_1_fu_1403_p4 = {{sub_ln1148_fu_1398_p2[32:1]}};

assign trunc_ln1148_2_fu_1419_p4 = {{ret_V_17_reg_2043[32:1]}};

assign trunc_ln1148_3_fu_932_p4 = {{ret_V_15_reg_1754_pp1_iter5_reg[32:1]}};

assign trunc_ln1148_4_fu_1448_p4 = {{sub_ln1148_2_fu_1443_p2[32:1]}};

assign trunc_ln1148_5_fu_1464_p4 = {{ret_V_18_reg_2050[32:1]}};

assign trunc_ln1148_6_fu_740_p4 = {{ret_V_fu_720_p2[32:1]}};

assign trunc_ln1148_8_fu_903_p4 = {{ret_V_14_reg_1717_pp1_iter5_reg[32:1]}};

assign trunc_ln1148_9_fu_756_p4 = {{sub_ln1148_8_fu_734_p2[32:1]}};

assign trunc_ln117_fu_1064_p1 = ap_phi_mux_i_2_phi_fu_483_p4[9:0];

assign trunc_ln119_fu_1068_p1 = ap_phi_mux_i_2_phi_fu_483_p4[8:0];

assign trunc_ln145_fu_497_p1 = din_V_TDATA_int_regslice[31:0];

integer ap_tvar_int_0;

always @ (i_3171_reg_456) begin
    for (ap_tvar_int_0 = 9 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 9 - 1) begin
            trunc_ln1_fu_515_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            trunc_ln1_fu_515_p4[ap_tvar_int_0] = i_3171_reg_456[9 - ap_tvar_int_0];
        end
    end
end

assign trunc_ln5_fu_967_p4 = {{ret_V_5_fu_963_p2[62:31]}};

assign trunc_ln703_1_fu_1086_p1 = sub_ln703_2_fu_1080_p2[8:0];

assign trunc_ln703_fu_585_p1 = sub_ln703_fu_579_p2[8:0];

assign trunc_ln708_3_fu_1565_p4 = {{ret_V_13_fu_1561_p2[62:31]}};

assign trunc_ln95_fu_559_p1 = ap_phi_mux_i_1_phi_fu_471_p4[9:0];

assign trunc_ln97_fu_563_p1 = ap_phi_mux_i_1_phi_fu_471_p4[8:0];

assign twid_rom_M_imag_V_address0 = zext_ln95_fu_605_p1;

assign twid_rom_M_real_V_address0 = zext_ln95_fu_605_p1;

assign twid_rom_conj_M_imag_V_address0 = zext_ln117_fu_1106_p1;

assign twid_rom_conj_M_real_V_address0 = zext_ln117_fu_1106_p1;

assign y1_M_imag_fu_636_p3 = ((icmp_ln97_fu_622_p2[0:0] == 1'b1) ? descramble_buf_0_M_imag_V_q1 : descramble_buf_1_M_imag_V_q1);

assign y1_M_real_fu_628_p3 = ((icmp_ln97_fu_622_p2[0:0] == 1'b1) ? descramble_buf_0_M_real_V_q1 : descramble_buf_1_M_real_V_q1);

assign zext_ln1115_fu_1328_p1 = r_V_10_fu_1308_p3;

assign zext_ln1118_fu_1013_p1 = shl_ln_fu_1003_p3;

assign zext_ln117_fu_1106_p1 = i_2_reg_479;

assign zext_ln119_fu_1072_p1 = trunc_ln119_fu_1068_p1;

assign zext_ln703_1_fu_1090_p1 = trunc_ln703_1_fu_1086_p1;

assign zext_ln703_fu_589_p1 = trunc_ln703_fu_585_p1;

assign zext_ln92_fu_525_p1 = trunc_ln1_fu_515_p4;

assign zext_ln95_fu_605_p1 = i_1_reg_467;

assign zext_ln97_fu_567_p1 = trunc_ln97_fu_563_p1;

endmodule //hls_xfft2real_xfft2real_complex_ap_fixed_32_1_5_3_0_complex_ap_fixed_32_1_5_3_0_11_true_s
