#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : soc.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Wed May 18 01:04:25 +0800 2022
# SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved. 
#
# usage: soc.sh [-help]
# usage: soc.sh [-lib_map_path]
# usage: soc.sh [-noclean_files]
# usage: soc.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'soc.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm xil_defaultlib xbip_utils_v3_0_10 axi_utils_v2_0_6 c_reg_fd_v12_0_6 xbip_dsp48_wrapper_v3_0_4 xbip_pipe_v3_0_6 xbip_dsp48_addsub_v3_0_6 xbip_addsub_v3_0_6 c_addsub_v12_0_14 c_mux_bit_v12_0_6 c_shift_ram_v12_0_14 xbip_bram18k_v3_0_6 mult_gen_v12_0_16 cmpy_v6_0_19 floating_point_v7_0_18 xfft_v9_1_5 xlconstant_v1_1_7 lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 util_vector_logic_v2_0_1 blk_mem_gen_v8_4_4 fifo_generator_v13_1_4 xdma_v4_1_8 axi_lite_ipif_v3_0_4 interrupt_control_v3_1_4 axi_gpio_v2_0_24 generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_22 fifo_generator_v13_2_5 axi_data_fifo_v2_1_21 axi_crossbar_v2_1_23 lib_pkg_v1_0_2 axi_timer_v2_0_24 lib_srl_fifo_v1_0_2 axi_uartlite_v2_0_26 xlconcat_v2_1_4 axi_protocol_converter_v2_1_22 axi_clock_converter_v2_1_21 axi_dwidth_converter_v2_1_22)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "soc.sh - Script generated by export_simulation (Vivado v2020.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../bd/soc/ipshared/ea75/rtl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/d0f7" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ea75/rtl" +incdir+"D:/Soft/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "D:/Soft/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "D:/Soft/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "D:/Soft/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "D:/Soft/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "D:/Soft/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "D:/Soft/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "D:/Soft/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "D:/Soft/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "D:/Soft/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../bd/soc/ipshared/ea75/rtl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/d0f7" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ea75/rtl" +incdir+"D:/Soft/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "D:/Soft/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "D:/Soft/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "D:/Soft/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "D:/Soft/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../bd/soc/ipshared/ea75/rtl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/d0f7" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ea75/rtl" +incdir+"D:/Soft/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_config_fft_0_0/sim/soc_config_fft_0_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_format_conversion_0_0/sim/soc_format_conversion_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_utils_v3_0_10 $vhdlan_opts \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/d117/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_utils_v2_0_6 $vhdlan_opts \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/1971/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_reg_fd_v12_0_6 $vhdlan_opts \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/edec/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/cdbf/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/7468/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/910d/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/cfdd/hdl/xbip_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_addsub_v12_0_14 $vhdlan_opts \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ebb8/hdl/c_addsub_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_mux_bit_v12_0_6 $vhdlan_opts \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ecb4/hdl/c_mux_bit_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_shift_ram_v12_0_14 $vhdlan_opts \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/2598/hdl/c_shift_ram_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_bram18k_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/d367/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_16 $vhdlan_opts \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ce84/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work cmpy_v6_0_19 $vhdlan_opts \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/0e0f/hdl/cmpy_v6_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work floating_point_v7_0_18 $vhdlan_opts \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/f1e3/hdl/floating_point_v7_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xfft_v9_1_5 $vhdlan_opts \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/58b9/hdl/xfft_v9_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/soc/ip/soc_xfft_0_0/sim/soc_xfft_0_0.vhd" \
    "$ref_dir/../../../bd/soc/ip/soc_xfft_0_1/sim/soc_xfft_0_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../bd/soc/ipshared/ea75/rtl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/d0f7" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ea75/rtl" +incdir+"D:/Soft/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/fcfc/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../bd/soc/ipshared/ea75/rtl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/d0f7" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ea75/rtl" +incdir+"D:/Soft/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_xlconstant_0_0/sim/soc_xlconstant_0_0.v" \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/7226/hdl/verilog/hls_xfft2real_mul_32s_30ns_62_3_1.v" \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/7226/hdl/verilog/hls_xfft2real_mul_32s_31ns_62_3_1.v" \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/7226/hdl/verilog/hls_xfft2real_mul_32s_31ns_63_3_1.v" \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/7226/hdl/verilog/hls_xfft2real_mul_32s_32s_63_3_1.v" \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/7226/hdl/verilog/hls_xfft2real_regslice_both.v" \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/7226/hdl/verilog/hls_xfft2real_xfft2real_complex_ap_fixed_32_1_5_3_0_complex_ap_fixed_32_1_5_3_0_11_true_s.v" \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/7226/hdl/verilog/hls_xfft2real_xfft2real_complex_ap_fixed_32_1_5_3_0_complex_ap_fixed_32_1_5_3_0_11_true_s_dg8j.v" \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/7226/hdl/verilog/hls_xfft2real_xfft2real_complex_ap_fixed_32_1_5_3_0_complex_ap_fixed_32_1_5_3_0_11_true_s_fdEe.v" \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/7226/hdl/verilog/hls_xfft2real_xfft2real_complex_ap_fixed_32_1_5_3_0_complex_ap_fixed_32_1_5_3_0_11_true_s_fkbM.v" \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/7226/hdl/verilog/hls_xfft2real_xfft2real_complex_ap_fixed_32_1_5_3_0_complex_ap_fixed_32_1_5_3_0_11_true_s_tbkb.v" \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/7226/hdl/verilog/hls_xfft2real_xfft2real_complex_ap_fixed_32_1_5_3_0_complex_ap_fixed_32_1_5_3_0_11_true_s_tcud.v" \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/7226/hdl/verilog/hls_xfft2real_xfft2real_complex_ap_fixed_32_1_5_3_0_complex_ap_fixed_32_1_5_3_0_11_true_s_tfYi.v" \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/7226/hdl/verilog/hls_xfft2real.v" \
    "$ref_dir/../../../bd/soc/ip/soc_hls_xfft2real_1_0/sim/soc_hls_xfft2real_1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/soc/ip/soc_proc_sys_reset_0_0/sim/soc_proc_sys_reset_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work util_vector_logic_v2_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../bd/soc/ipshared/ea75/rtl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/d0f7" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ea75/rtl" +incdir+"D:/Soft/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/3f90/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../bd/soc/ipshared/ea75/rtl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/d0f7" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ea75/rtl" +incdir+"D:/Soft/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_util_vector_logic_0_0/sim/soc_util_vector_logic_0_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_read_data_unit_0_1/sim/soc_read_data_unit_0_1.v" \
    "$ref_dir/../../../bd/soc/ip/soc_backproject_0_2/sim/soc_backproject_0_2.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_axi_ctrl_addr_decode.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_axi_ctrl_read.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_axi_ctrl_reg.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_axi_ctrl_reg_bank.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_axi_ctrl_top.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_axi_ctrl_write.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_axi_mc.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_axi_mc_ar_channel.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_axi_mc_aw_channel.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_axi_mc_b_channel.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_axi_mc_cmd_arbiter.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_axi_mc_cmd_fsm.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_axi_mc_cmd_translator.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_axi_mc_fifo.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_axi_mc_incr_cmd.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_axi_mc_r_channel.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_axi_mc_simple_fifo.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_axi_mc_wrap_cmd.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_axi_mc_wr_cmd_fsm.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_axi_mc_w_channel.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_ddr_axic_register_slice.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_ddr_axi_register_slice.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_ddr_axi_upsizer.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_ddr_a_upsizer.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_ddr_carry_and.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_ddr_carry_latch_and.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_ddr_carry_latch_or.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_ddr_carry_or.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_ddr_command_fifo.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_ddr_comparator.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_ddr_comparator_sel.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_ddr_comparator_sel_static.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_ddr_r_upsizer.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/axi/mig_7series_v4_2_ddr_w_upsizer.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/clocking/mig_7series_v4_2_clk_ibuf.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/clocking/mig_7series_v4_2_infrastructure.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/clocking/mig_7series_v4_2_iodelay_ctrl.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/clocking/mig_7series_v4_2_tempmon.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_2_arb_mux.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_2_arb_row_col.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_2_arb_select.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_2_bank_cntrl.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_2_bank_common.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_2_bank_compare.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_2_bank_mach.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_2_bank_queue.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_2_bank_state.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_2_col_mach.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_2_mc.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_2_rank_cntrl.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_2_rank_common.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_2_rank_mach.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/controller/mig_7series_v4_2_round_robin_arb.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/ecc/mig_7series_v4_2_ecc_buf.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/ecc/mig_7series_v4_2_ecc_dec_fix.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/ecc/mig_7series_v4_2_ecc_gen.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/ecc/mig_7series_v4_2_ecc_merge_enc.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/ecc/mig_7series_v4_2_fi_xor.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/ip_top/mig_7series_v4_2_memc_ui_top_axi.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/ip_top/mig_7series_v4_2_mem_intfc.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_byte_group_io.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_byte_lane.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_calib_top.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_if_post_fifo.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_mc_phy.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_mc_phy_wrapper.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_of_pre_fifo.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_4lanes.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ck_addr_cmd_delay.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_dqs_found_cal.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_dqs_found_cal_hr.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_init.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_cntlr.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_data.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_edge.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_lim.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_mux.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_po_cntlr.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_ocd_samp.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_oclkdelay_cal.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_prbs_rdlvl.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_rdlvl.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_tempmon.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_top.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_wrcal.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_wrlvl.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_phy_wrlvl_off_delay.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_prbs_gen.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_ddr_skip_calib_tap.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_poc_cc.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_poc_edge_store.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_poc_meta.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_poc_pd.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_poc_tap_base.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/phy/mig_7series_v4_2_poc_top.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/ui/mig_7series_v4_2_ui_cmd.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/ui/mig_7series_v4_2_ui_rd_data.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/ui/mig_7series_v4_2_ui_top.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/ui/mig_7series_v4_2_ui_wr_data.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/soc_mig_7series_0_1_mig_sim.v" \
    "$ref_dir/../../../bd/soc/ip/soc_mig_7series_0_1/soc_mig_7series_0_1/user_design/rtl/soc_mig_7series_0_1.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_0/source/soc_xdma_0_1_pcie2_ip_pipe_clock.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_0/source/soc_xdma_0_1_pcie2_ip_pipe_eq.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_0/source/soc_xdma_0_1_pcie2_ip_pipe_drp.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_0/source/soc_xdma_0_1_pcie2_ip_pipe_rate.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_0/source/soc_xdma_0_1_pcie2_ip_pipe_reset.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_0/source/soc_xdma_0_1_pcie2_ip_pipe_sync.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_0/source/soc_xdma_0_1_pcie2_ip_gtp_pipe_rate.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_0/source/soc_xdma_0_1_pcie2_ip_gtp_pipe_drp.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_0/source/soc_xdma_0_1_pcie2_ip_gtp_pipe_reset.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_0/source/soc_xdma_0_1_pcie2_ip_pipe_user.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_0/source/soc_xdma_0_1_pcie2_ip_pipe_wrapper.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_0/source/soc_xdma_0_1_pcie2_ip_qpll_drp.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_0/source/soc_xdma_0_1_pcie2_ip_qpll_reset.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_0/source/soc_xdma_0_1_pcie2_ip_qpll_wrapper.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_0/source/soc_xdma_0_1_pcie2_ip_rxeq_scan.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_0/source/soc_xdma_0_1_pcie2_ip_pcie_top.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_0/source/soc_xdma_0_1_pcie2_ip_core_top.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_0/source/soc_xdma_0_1_pcie2_ip_axi_basic_rx_null_gen.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_0/source/soc_xdma_0_1_pcie2_ip_axi_basic_rx_pipeline.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_0/source/soc_xdma_0_1_pcie2_ip_axi_basic_rx.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_0/source/soc_xdma_0_1_pcie2_ip_axi_basic_top.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_0/source/soc_xdma_0_1_pcie2_ip_axi_basic_tx_pipeline.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_0/source/soc_xdma_0_1_pcie2_ip_axi_basic_tx_thrtl_ctl.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_0/source/soc_xdma_0_1_pcie2_ip_axi_basic_tx.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_0/source/soc_xdma_0_1_pcie2_ip_pcie_7x.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_0/source/soc_xdma_0_1_pcie2_ip_pcie_bram_7x.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_0/source/soc_xdma_0_1_pcie2_ip_pcie_bram_top_7x.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_0/source/soc_xdma_0_1_pcie2_ip_pcie_brams_7x.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_0/source/soc_xdma_0_1_pcie2_ip_pcie_pipe_lane.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_0/source/soc_xdma_0_1_pcie2_ip_pcie_pipe_misc.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_0/source/soc_xdma_0_1_pcie2_ip_pcie_pipe_pipeline.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_0/source/soc_xdma_0_1_pcie2_ip_gt_top.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_0/source/soc_xdma_0_1_pcie2_ip_gt_common.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_0/source/soc_xdma_0_1_pcie2_ip_gtp_cpllpd_ovrd.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_0/source/soc_xdma_0_1_pcie2_ip_gtx_cpllpd_ovrd.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_0/source/soc_xdma_0_1_pcie2_ip_gt_rx_valid_filter_7x.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_0/source/soc_xdma_0_1_pcie2_ip_gt_wrapper.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_0/source/soc_xdma_0_1_pcie2_ip_pcie2_top.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_0/sim/soc_xdma_0_1_pcie2_ip.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_4_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../bd/soc/ipshared/ea75/rtl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/d0f7" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ea75/rtl" +incdir+"D:/Soft/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/2985/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../bd/soc/ipshared/ea75/rtl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/d0f7" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ea75/rtl" +incdir+"D:/Soft/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_1/sim/xdma_v4_1_8_blk_mem_64_reg_be.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_2/sim/xdma_v4_1_8_blk_mem_64_noreg_be.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../bd/soc/ipshared/ea75/rtl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/d0f7" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ea75/rtl" +incdir+"D:/Soft/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/e6d5/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_1_4 $vhdlan_opts \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/e6d5/hdl/fifo_generator_v13_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../bd/soc/ipshared/ea75/rtl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/d0f7" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ea75/rtl" +incdir+"D:/Soft/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/e6d5/hdl/fifo_generator_v13_1_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../bd/soc/ipshared/ea75/rtl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/d0f7" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ea75/rtl" +incdir+"D:/Soft/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_3/sim/pcie2_fifo_generator_dma_cpl.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/ip_4/sim/pcie2_fifo_generator_tgt_brdg.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xdma_v4_1_8 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../bd/soc/ipshared/ea75/rtl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/d0f7" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ea75/rtl" +incdir+"D:/Soft/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/cc3e/hdl/xdma_v4_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../bd/soc/ipshared/ea75/rtl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/d0f7" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ea75/rtl" +incdir+"D:/Soft/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/xdma_v4_1/hdl/verilog/soc_xdma_0_1_dma_cpl.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/xdma_v4_1/hdl/verilog/soc_xdma_0_1_dma_req.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/xdma_v4_1/hdl/verilog/soc_xdma_0_1_rx_destraddler.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/xdma_v4_1/hdl/verilog/soc_xdma_0_1_rx_demux.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/xdma_v4_1/hdl/verilog/soc_xdma_0_1_tgt_cpl.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/xdma_v4_1/hdl/verilog/soc_xdma_0_1_tgt_req.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/xdma_v4_1/hdl/verilog/soc_xdma_0_1_tx_mux.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/xdma_v4_1/hdl/verilog/soc_xdma_0_1_axi_stream_intf.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/xdma_v4_1/hdl/verilog/soc_xdma_0_1_cfg_sideband.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/xdma_v4_1/hdl/verilog/soc_xdma_0_1_pcie2_to_pcie3_wrapper.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/xdma_v4_1/hdl/verilog/soc_xdma_0_1_dma_bram_wrap.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/xdma_v4_1/hdl/verilog/soc_xdma_0_1_dma_bram_wrap_1024.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/xdma_v4_1/hdl/verilog/soc_xdma_0_1_dma_bram_wrap_2048.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/xdma_v4_1/hdl/verilog/soc_xdma_0_1_core_top.sv" \
    "$ref_dir/../../../bd/soc/ip/soc_xdma_0_1/sim/soc_xdma_0_1.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/soc/ip/soc_util_ds_buf_1_0/util_ds_buf.vhd" \
    "$ref_dir/../../../bd/soc/ip/soc_util_ds_buf_1_0/sim/soc_util_ds_buf_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../bd/soc/ipshared/ea75/rtl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/d0f7" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ea75/rtl" +incdir+"D:/Soft/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ipshared/ea75/rtl/cm3_dap_ahb_ap.v" \
    "$ref_dir/../../../bd/soc/ipshared/ea75/rtl/cm3_wic.v" \
    "$ref_dir/../../../bd/soc/ipshared/ea75/rtl/cm3_nvic.v" \
    "$ref_dir/../../../bd/soc/ipshared/ea75/rtl/cm3_dwt.v" \
    "$ref_dir/../../../bd/soc/ipshared/ea75/rtl/AhbToAxi.v" \
    "$ref_dir/../../../bd/soc/ipshared/ea75/rtl/cm3_mpu.v" \
    "$ref_dir/../../../bd/soc/ipshared/ea75/rtl/cm3_bus_matrix.v" \
    "$ref_dir/../../../bd/soc/ipshared/ea75/rtl/models.v" \
    "$ref_dir/../../../bd/soc/ipshared/ea75/rtl/cmsdk.v" \
    "$ref_dir/../../../bd/soc/ipshared/ea75/rtl/cm3_tpiu.v" \
    "$ref_dir/../../../bd/soc/ipshared/ea75/rtl/dapswjdp.v" \
    "$ref_dir/../../../bd/soc/ipshared/ea75/rtl/cm3_fpb.v" \
    "$ref_dir/../../../bd/soc/ipshared/ea75/rtl/cm3_dpu.v" \
    "$ref_dir/../../../bd/soc/ipshared/ea75/rtl/cm3_itm.v" \
    "$ref_dir/../../../bd/soc/ipshared/ea75/rtl/cm3_etm.v" \
    "$ref_dir/../../../bd/soc/ipshared/ea75/rtl/cortexm3.v" \
    "$ref_dir/../../../bd/soc/ipshared/ea75/rtl/cortexm3_integration.v" \
    "$ref_dir/../../../bd/soc/ip/soc_CORTEXM3_AXI_0_0/sim/soc_CORTEXM3_AXI_0_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_acc_configurator_v1_0_0_0/sim/soc_acc_configurator_v1_0_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_24 $vhdlan_opts \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/4318/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/soc/ip/soc_axi_gpio_0_0/sim/soc_axi_gpio_0_0.vhd" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_gpio_0_1/sim/soc_axi_gpio_0_1.vhd" \
    "$ref_dir/../../../bd/soc/ip/soc_axi_gpio_0_2/sim/soc_axi_gpio_0_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../bd/soc/ipshared/ea75/rtl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/d0f7" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ea75/rtl" +incdir+"D:/Soft/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../bd/soc/ipshared/ea75/rtl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/d0f7" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ea75/rtl" +incdir+"D:/Soft/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../bd/soc/ipshared/ea75/rtl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/d0f7" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ea75/rtl" +incdir+"D:/Soft/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/af2c/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../bd/soc/ipshared/ea75/rtl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/d0f7" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ea75/rtl" +incdir+"D:/Soft/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/276e/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_5 $vhdlan_opts \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/276e/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../bd/soc/ipshared/ea75/rtl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/d0f7" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ea75/rtl" +incdir+"D:/Soft/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/276e/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../bd/soc/ipshared/ea75/rtl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/d0f7" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ea75/rtl" +incdir+"D:/Soft/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/54c0/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_23 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../bd/soc/ipshared/ea75/rtl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/d0f7" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ea75/rtl" +incdir+"D:/Soft/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/bc0a/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../bd/soc/ipshared/ea75/rtl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/d0f7" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ea75/rtl" +incdir+"D:/Soft/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_xbar_3/sim/soc_xbar_3.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xbar_4/sim/soc_xbar_4.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xbar_5/sim/soc_xbar_5.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_timer_v2_0_24 $vhdlan_opts \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/70d6/hdl/axi_timer_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/soc/ip/soc_axi_timer_0_0/sim/soc_axi_timer_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_uartlite_v2_0_26 $vhdlan_opts \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/5edb/hdl/axi_uartlite_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/soc/ip/soc_axi_uartlite_0_0/sim/soc_axi_uartlite_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../bd/soc/ipshared/ea75/rtl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/d0f7" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ea75/rtl" +incdir+"D:/Soft/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_clk_wiz_0_0/soc_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/soc/ip/soc_clk_wiz_0_0/soc_clk_wiz_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/soc/ip/soc_proc_sys_reset_0_1/sim/soc_proc_sys_reset_0_1.vhd" \
    "$ref_dir/../../../bd/soc/ip/soc_proc_sys_reset_1_0/sim/soc_proc_sys_reset_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../bd/soc/ipshared/ea75/rtl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/d0f7" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ea75/rtl" +incdir+"D:/Soft/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_swdio_tri_buffer_0_0/sim/soc_swdio_tri_buffer_0_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_util_vector_logic_0_1/sim/soc_util_vector_logic_0_1.v" \
    "$ref_dir/../../../bd/soc/ip/soc_util_vector_logic_0_2/sim/soc_util_vector_logic_0_2.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconcat_v2_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../bd/soc/ipshared/ea75/rtl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/d0f7" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ea75/rtl" +incdir+"D:/Soft/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/4b67/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../bd/soc/ipshared/ea75/rtl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/d0f7" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ea75/rtl" +incdir+"D:/Soft/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_xlconcat_0_0/sim/soc_xlconcat_0_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xlconstant_0_1/sim/soc_xlconstant_0_1.v" \
    "$ref_dir/../../../bd/soc/ip/soc_xlconstant_1_0/sim/soc_xlconstant_1_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../bd/soc/ipshared/ea75/rtl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/d0f7" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ea75/rtl" +incdir+"D:/Soft/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/5cee/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../bd/soc/ipshared/ea75/rtl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/d0f7" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ea75/rtl" +incdir+"D:/Soft/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_auto_pc_1/sim/soc_auto_pc_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../bd/soc/ipshared/ea75/rtl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/d0f7" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ea75/rtl" +incdir+"D:/Soft/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/1304/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../bd/soc/ipshared/ea75/rtl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/d0f7" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ea75/rtl" +incdir+"D:/Soft/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/2394/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/cc3e/hdl/verilog" +incdir+"$ref_dir/../../../bd/soc/ipshared/ea75/rtl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/d0f7" +incdir+"$ref_dir/../../../../cm3_soc.gen/sources_1/bd/soc/ipshared/ea75/rtl" +incdir+"D:/Soft/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/soc/ip/soc_auto_us_0/sim/soc_auto_us_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_auto_cc_0/sim/soc_auto_cc_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_auto_cc_1/sim/soc_auto_cc_1.v" \
    "$ref_dir/../../../bd/soc/ip/soc_auto_ds_0/sim/soc_auto_ds_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_auto_pc_0/sim/soc_auto_pc_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_s00_data_fifo_0/sim/soc_s00_data_fifo_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_auto_us_df_0/sim/soc_auto_us_df_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_auto_us_df_1/sim/soc_auto_us_df_1.v" \
    "$ref_dir/../../../bd/soc/ip/soc_auto_us_cc_df_0/sim/soc_auto_us_cc_df_0.v" \
    "$ref_dir/../../../bd/soc/ip/soc_auto_ds_1/sim/soc_auto_ds_1.v" \
    "$ref_dir/../../../bd/soc/sim/soc.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.soc xil_defaultlib.glbl -o soc_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./soc_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./soc.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key soc_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc soc_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./soc.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: soc.sh [-help]\n\
Usage: soc.sh [-lib_map_path]\n\
Usage: soc.sh [-reset_run]\n\
Usage: soc.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
